/* PIC14 mid-range family selectors for PIC16F628A: single part, no
 * PIR2/SSP/ADC/CCP2/PSP/PORTC/D/E. Shared pic14-midrange-core code
 * includes this name; each family's copy resolves via the path. */

#ifndef PIC14_MIDRANGE_H
#define PIC14_MIDRANGE_H
#include "pic16f628a_hal.h"

/* Capability contract for shared pic14-midrange-core code (1 = present). */
#define PIC14MIDRANGE_FLASH_KW 2
#define PIC14MIDRANGE_HAS_PIR2 0
#define PIC14MIDRANGE_HAS_SSP 0
#define PIC14MIDRANGE_HAS_ADC 0
#define PIC14MIDRANGE_HAS_CCP2 0
#define PIC14MIDRANGE_HAS_PSP 0
#define PIC14MIDRANGE_HAS_PORTC 0
#define PIC14MIDRANGE_HAS_PORTD 0
#define PIC14MIDRANGE_HAS_PORTE 0
#define PIC14MIDRANGE_HAS_COMP_DUAL 0
#define PIC14MIDRANGE_HAS_ULPWU 0
#define PIC14MIDRANGE_HAS_OSF 0
#define PIC14MIDRANGE_HAS_CM_PIR1 1
#define PIC14MIDRANGE_HAS_EE_PIR1 1
#define PIC14MIDRANGE_HAS_CMCON_BANK0 1
#define PIC14MIDRANGE_HAS_EEPROM_BANK1 1
#define PIC14MIDRANGE_HAS_BRGH16 0
#define PIC14MIDRANGE_HAS_TMR1_GATE 0
#define PIC14MIDRANGE_HAS_ECCP 0
#define PIC14MIDRANGE_HAS_VRSS 0
#define PIC14MIDRANGE_HAS_WDT_SW 0
#define PIC14MIDRANGE_HAS_ANSEL 0
#define PIC14MIDRANGE_HAS_OSCCON 0
#define PIC14MIDRANGE_HAS_BCL_DISPATCH 0
#define PIC14MIDRANGE_HAS_VRCON 1
#define PIC14MIDRANGE_PORTA_MASK 0xDFU
#endif /* PIC14_MIDRANGE_H */
