/**
 * @file    combo_rb_uart.c
 * @brief   C4 of the combination matrix
 *          (docs/superpowers/plans/2026-08-09-combination-matrix.md):
 *          PORTB change ISR + USART TX + TIMER2 interleaved, all real
 *          code, one firmware, one bank state.
 *
 * @details
 *   The bug classes this gate hunts:
 *   - The RB<7:4> change path under a live TIMER2 ISR: the dispatcher
 *     reads INTCON once per ISR entry and can service RBIF and TMR2IF
 *     in the same entry; the RB handler must read PORTB before
 *     clearing RBIF (DS39582B 14.11.3), and the callback must run
 *     exactly once per pending flag.
 *   - Bank corruption: TIMER2 and the RB handler both run inside the
 *     ISR while the main line interleaves polled USART TX (a Bank-1
 *     TXSTA read per poll via EPIC_BANK1_READ8). A misdirected
 *     TXSTA read wedges the TSR-empty wait, which stalls the run and
 *     never emits the marker; a corrupted TXREG write garbles the
 *     capture.
 *   - GIE health: RBIF asserted from firmware (the documented
 *     test-only fallback, same pattern as pic16f87xa-hal/tests/
 *     example_rb_change.c) must be serviced exactly once per assert
 *     while GIE stays set and the timer keeps firing.
 *
 *   MPLAB SIM cannot drive a pin from the firmware's own run (the
 *   runner's only script hook, EXTRA_MDB, runs after halt), so the
 *   port-change event is generated by asserting RBIF in INTCON from
 *   the main line instead of changing a real pin level. RBIF is a
 *   plain R/W bit; the interrupt path it arms is the same one a real
 *   RB<7:4> mismatch uses. Each assert is followed by a bounded wait
 *   for the callback before the next assert, so one callback per
 *   pending flag is verifiable exactly.
 *
 *   MPLAB SIM behavior pinned by this gate's own diagnostic builds
 *   (2026-08-09; the host simulator models none of this, so these are
 *   simulator gaps, not firmware bugs):
 *   - An interrupt taken while the CPU is inside the polled-TX
 *     TSR-empty wait (`while (!EPIC_USART_IsTxShiftRegisterEmpty())`)
 *     can wedge the sim's ISR path: GIE is left cleared and the
 *     vector is never entered, so the ISR stops firing for the rest
 *     of the pass (deterministic per build; the count froze at the
 *     take landing in the wait loop, at a different take index per
 *     loop shape). C1's gate never hit this because its only TX is
 *     the final marker, after EPIC_IRQ_Disable(). This gate follows
 *     the same shape: the run loop is TX-free, and all TX (the
 *     deterministic frames plus the marker) happens after the checks
 *     with GIE off. The byte-exact frame payload in the mdb UART
 *     capture is the TX integrity evidence.
 *   - The GIE-on edge with a pending timer flag wedges the sim (the
 *     Finding 10.1 class, C1's lesson): the timer is stopped and its
 *     flag cleared BEFORE EPIC_IRQ_Restore(1), per pass.
 *
 *   Bounded and self-reporting (the harness contract); no RX
 *   involvement, so the MPLAB SIM RX wall does not apply.
 */

#include "core/epic_harness.h"
#include "core/pic16_irq.h"
#include "peripherals/pic16f87xa_gpio.h"
#include "peripherals/pic16f87xa_timer2.h"
#include "peripherals/pic16f87xa_usart.h"
#include "target/pic16f87xa_platform.h"

#include <stdint.h>

#ifndef FOSC_HZ
#define FOSC_HZ 20000000UL
#endif

#define SIM_ITERATIONS 8000UL

/* Same fast TIMER2 as the C1 gate: ~200 us period at 20 MHz
 * (instruction clock 5 MHz, prescaler 1:16 -> 312.5 kHz -> 62.5
 * counts), so the ISR load on the main line is comparable. */
#define T2_PRESCALER TIMER2_PRESCALER_1_16
#define T2_PERIOD    62u

/* One RB event (assert RBIF, wait for the callback) every 200 main
 * iterations: 40 events total, spread across the run, all under the
 * live TMR2 ISR. */
#define RB_EVENTS       40u
#define RB_EVENT_EVERY  200u
#define RB_WAIT_LIMIT   2000u

/* Post-check TX frames: deterministic payload for the capture. */
#define TX_FRAMES       8u

/* RB4..RB7 driven high: the callback must receive the freshly-read
 * PORTB with that nibble intact (read-before-clear ordering). */
#define RB_DRIVEN_NIBBLE 0xF0u

static uint16_t g_t2_count = 0u;
static uint16_t g_rb_count = 0u;
static uint8_t  g_rb_last = 0u;
static uint16_t g_fail = 0u;

static void t2_overflow_cb(void)
{
    g_t2_count++;
}

static void rb_change_cb(uint8_t portb_value)
{
    g_rb_count++;
    g_rb_last = portb_value;
}

static void fail(uint8_t idx)
{
    static const char hx[] = "0123456789ABCDEF";
    char c[2];
    g_fail++;
    epic_harness_log("F");
    c[0] = hx[(idx >> 4) & 0xF];
    c[1] = '\0';
    epic_harness_log(c);
    c[0] = hx[idx & 0xF];
    c[1] = '\0';
    epic_harness_log(c);
    epic_harness_log(".");
}

#define CHECK(cond, idx) do {         \
    if (!(cond)) fail(idx);            \
} while (0)

static void s_tx_noop(void)
{
}

/* Two hex digits for the frame index / checksum fields, computed
 * arithmetically. */
static void tx_hex2(uint8_t v)
{
    char c[2];
    uint8_t n = (v >> 4) & 0xFu;
    c[0] = (char)((n < 10u) ? ('0' + n) : ('A' + n - 10u));
    c[1] = '\0';
    epic_harness_log(c);
    n = v & 0xFu;
    c[0] = (char)((n < 10u) ? ('0' + n) : ('A' + n - 10u));
    c[1] = '\0';
    epic_harness_log(c);
}

/* Deterministic polled-TX frame: 'T' <idx:2 hex> <idx^0x5A:2 hex> '.'
 * The checksum byte lets the capture be verified byte-exact. */
static void send_frame(uint8_t idx)
{
    epic_harness_log("T");
    tx_hex2(idx);
    tx_hex2((uint8_t)(idx ^ 0x5Au));
    epic_harness_log(".");
}

int main(void)
{
    /* Per-pass reset: on this target main re-runs from the start
     * after returning (the crt's `ljmp start`), so the exact-count
     * checks below need self-contained counters per pass. GIE is 0
     * here (the previous pass disabled it before its checks). */
    g_t2_count = 0u;
    g_rb_count = 0u;
    g_rb_last = 0u;
    g_fail = 0u;

    epic_harness_init(SIM_ITERATIONS);

    /* USART: the harness already inited it; re-init with the no-op
     * callback handle (arms TXEN) and turn the TX interrupt source off
     * (transmission is polled, exactly like the C1 gate). */
    {
        USART_HandleTypeDef h = USART_HANDLE_DEFAULT;
        h.SPBRG = (uint8_t)USART_ComputeSPBRG(
            FOSC_HZ, 9600UL, USART_MODE_ASYNCHRONOUS, USART_BRGH_HIGH);
        h.TxCpltCallback = s_tx_noop;
        (void)EPIC_USART_Init(&h);
        EPIC_IRQ_DisableSrc(PIC16_IRQ_USART_TX);
    }

    /* PORTB: drive RB4..RB7 high as outputs, then read PORTB back to
     * re-arm the mismatch comparator before RBIF is cleared (on real
     * silicon the latch write itself can latch a mismatch; the read
     * ends it). Register the change callback. */
    EPIC_GPIO_Init(GPIOB, (uint16_t)(GPIO_PIN_4 | GPIO_PIN_5 |
                                     GPIO_PIN_6 | GPIO_PIN_7),
                   GPIO_MODE_OUTPUT);
    EPIC_GPIO_WritePin(GPIOB, RB_DRIVEN_NIBBLE, GPIO_PIN_SET);
    (void)EPIC_GPIO_ReadPort(GPIOB);
    EPIC_GPIO_RegisterChangeCallback(rb_change_cb);

    /* GIE discipline (C1 lesson): stop TMR2 and clear every pending
     * flag before the GIE-on edge, per pass; only then is RBIE
     * enabled and GIE restored, and TMR2 starts after GIE is on. */
    EPIC_REG8(PIC_REG_T2CON) &= (uint8_t)~0x04u;   /* TMR2ON = 0 */
    EPIC_IRQ_ClearFlag(PIC16_IRQ_TMR2);
    EPIC_IRQ_ClearFlag(PIC16_IRQ_RB);
    EPIC_IRQ_Enable(PIC16_IRQ_RB);
    EPIC_IRQ_Restore(1);

    /* TIMER2 with the overflow callback: enables TMR2IE. */
    TIMER2_HandleTypeDef t2 = TIMER2_HANDLE_DEFAULT;
    t2.Prescaler = T2_PRESCALER;
    t2.Period = T2_PERIOD;
    t2.OverflowCallback = t2_overflow_cb;
    (void)EPIC_TIMER2_Init(&t2);
    (void)EPIC_TIMER2_Start(&t2);

    /* Run loop: TX-free by design (see the header: an interrupt taken
     * inside the polled-TX TSR-empty wait can wedge the sim's ISR
     * path, so no TX happens while the ISR is being taken). The RB
     * events and the TMR2 ISR interleave here; every interrupt take
     * lands in plain loop code. */
    uint16_t rb_events = 0u;
    uint16_t evt_cd = RB_EVENT_EVERY;
    for (uint32_t i = 0; epic_harness_running(i); i++) {
        if (--evt_cd == 0u) {
            evt_cd = RB_EVENT_EVERY;
            if (rb_events < RB_EVENTS) {
                uint16_t before = g_rb_count;
                EPIC_REG8(PIC_REG_INTCON) |= PIC_INTCON_RBIF;
                uint16_t w = 0u;
                while ((g_rb_count == before) && (w < RB_WAIT_LIMIT)) {
                    w++;
                }
                rb_events++;
                CHECK(g_rb_count == before + 1u, 0x0B);   /* fired once */
                CHECK((g_rb_last & RB_DRIVEN_NIBBLE) == RB_DRIVEN_NIBBLE,
                      0x0C);                              /* PORTB intact */
                CHECK(EPIC_IRQ_GetFlag(PIC16_IRQ_RB) == 0u, 0x0D);
            }
        }
    }

    /* INTCON samples while the ISR is still live. The hardware clears
     * GIE for the duration of every ISR (~20% duty at the TMR2 rate),
     * so a single sample races the ISR; instead any sample observing
     * GIE set proves the wedge (GIE permanently clear) is absent. The
     * flag bits are stable: RBIF is serviced before each wait exits,
     * and INTF/TMR0IF are never set. */
    uint8_t gie_any = 0u;
    uint8_t rbif_any = 0u;
    uint8_t intf_any = 0u;
    uint8_t t0if_any = 0u;
    for (uint8_t k = 0u; k < 8u; k++) {
        uint8_t intcon = EPIC_REG8(PIC_REG_INTCON);
        if (intcon & PIC_INTCON_GIE) gie_any = 1u;
        if (intcon & PIC_INTCON_RBIF) rbif_any = 1u;
        if (intcon & PIC_INTCON_INTF) intf_any = 1u;
        if (intcon & PIC_INTCON_TMR0IF) t0if_any = 1u;
        for (volatile uint16_t d = 0u; d < 40u; d++) {
        }
    }
    EPIC_IRQ_Disable();

    /* Cross-checks. */
    uint8_t pie1 = 0u;
    EPIC_BANK1_READ8(PIE1, pie1);
    CHECK((pie1 & PIC_PIE1_TMR2IE) != 0u, 0x00);   /* source still enabled */
    CHECK((pie1 & (uint8_t)~(PIC_PIE1_TMR2IE)) == 0u, 0x01); /* nothing else */
    CHECK(g_t2_count >= 100u, 0x02);               /* timer kept firing */
    CHECK(g_rb_count == RB_EVENTS, 0x03);          /* one callback per flag */
    CHECK((g_rb_last & RB_DRIVEN_NIBBLE) == RB_DRIVEN_NIBBLE, 0x04);
    CHECK(gie_any != 0u, 0x05);                    /* GIE never wedged */
    CHECK(rbif_any == 0u, 0x06);                   /* RBIF always serviced */
    CHECK(intf_any == 0u, 0x07);                   /* no stray INT */
    CHECK(t0if_any == 0u, 0x08);                   /* no stray TMR0 */
    {
        uint8_t intcon = EPIC_REG8(PIC_REG_INTCON);
        CHECK((intcon & PIC_INTCON_RBIE) != 0u, 0x09);  /* RB source on */
        CHECK((intcon & PIC_INTCON_PEIE) != 0u, 0x0A);  /* peripheral IE on */
    }

    /* TX phase, with GIE off (the sim wedge class, see the header):
     * deterministic frames + the marker, byte-exact in the capture.
     * The verdict above is already fixed; this is the byte-exactness
     * evidence for the cross-check. */
    for (uint8_t f = 0u; f < TX_FRAMES; f++) {
        send_frame(f);
    }

    for (uint32_t i = 0; epic_harness_running(i); i++) {
        epic_harness_tick();
    }
    return epic_harness_report(g_fail == 0u);
}
