#!/usr/bin/env python3
"""Generate the file lists and consumer files for a self-contained
per-family source bundle (what someone outside the repo consumes).
Dependencies are flattened here at generation time, so the emitted
epicurus.mk is precomputed tables, not recursive make. Called by
scripts/make_bundle.py.
"""
from __future__ import annotations

import json
import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import epicmanifest  # noqa: E402


class BundleError(Exception):
    """A bundle that cannot be generated as asked."""


def _family(manifest, family_name):
    fam = manifest.families.get(family_name)
    if fam is None:
        known = ", ".join(sorted(manifest.families))
        raise BundleError(f"unknown family '{family_name}'; known: {known}")
    return fam


def modules_for_family(manifest, family_name: str) -> list[str]:
    """Every consumer module with at least one supported part in this family.

    Excludes a module whose dir equals the family's own hal_dir (the
    epic-pic16f193x-firmware shape: CI-coverage plumbing, not a library a
    consumer asks for) and any module whose dir sits under tests/ (the
    epic-combo-* modules: combination-matrix CI gates, not consumer
    libraries). Both are what keeps a bundle genuinely consumer-facing.
    """
    fam = _family(manifest, family_name)
    return sorted(
        name for name, mod in manifest.modules.items()
        if mod.supported.get(family_name)
        and mod.dir != fam.hal_dir
        and not mod.dir.startswith("tests/")
    )


def files_for_family(manifest, family_name: str) -> list[str]:
    """Every repo-root-relative source file a consumer bundle must carry.

    Sources only: the family HAL plus each consumer module's library
    sources, plus the manifest example sources that are consumer
    samples (under examples/). Manifest example sources elsewhere in a
    module (mcu/ size-check probes, tests/ real-target smoke tests)
    never ship. Headers/docs are copied by make_bundle.py's explicit
    allowlist; this is the list that has to be exactly right because
    it is what the emitted epicurus.mk names.
    """
    fam = _family(manifest, family_name)
    files = set(fam.hal_sources)
    files |= {c.path for c in fam.conditional_sources}

    for name in modules_for_family(manifest, family_name):
        mod = manifest.modules[name]
        files |= {os.path.normpath(f"{mod.dir}/{s}") for s in mod.sources}
        files |= {os.path.normpath(f"{mod.dir}/{s}") for s in mod.sources_by_family.get(family_name, [])}
        example = mod.examples.get(family_name)
        if example is not None:
            files |= {
                os.path.normpath(f"{mod.dir}/{s}")
                for s in example.sources
                if s.startswith("examples/")
            }

    return sorted(files)


def emit_epicurus_mk(manifest, family_name: str, version: str) -> str:
    """The consumer-facing make fragment.

    Data plus a guard, no build rules: the consumer's own Makefile owns
    the rules, and this file must not assume anything about them beyond
    the ability to `include` it. Dependency resolution is already done
    (see EPICURUS_RESOLVED_*), so nothing here recurses.
    """
    fam = _family(manifest, family_name)
    modules = modules_for_family(manifest, family_name)

    out = [
        "# GENERATED by scripts/bundlegen.py. Do not edit.",
        f"# Epicurus {version}, {family_name} family.",
        "#",
        "# Usage from your own Makefile:",
        "#",
        "#   EPICURUS_DIR := third_party/epicurus",
        "#   EPICURUS_MCU := 16F877A",
        "#   EPICURUS_MODULES := serial tick",
        "#   include $(EPICURUS_DIR)/epicurus.mk",
        "#",
        "#   SRCS := main.c $(EPICURUS_SRCS)",
        "#   CFLAGS += $(EPICURUS_CFLAGS)",
        "#",
        "# Sets EPICURUS_SRCS, EPICURUS_INCLUDES, and EPICURUS_CFLAGS.",
        "# Module names are given without the epic- prefix.",
        "",
        f"EPICURUS_VERSION := {version}",
        f"EPICURUS_FAMILY  := {family_name}",
        f"EPICURUS_DFP     := {fam.dfp}",
        f"EPICURUS_VARIANTS := {' '.join(fam.variants)}",
        "",
        "ifeq ($(strip $(EPICURUS_DIR)),)",
        "  $(error EPICURUS_DIR is not set: point it at this bundle's root)",
        "endif",
        "ifeq ($(strip $(EPICURUS_MCU)),)",
        "  $(error EPICURUS_MCU is not set: choose one of $(EPICURUS_VARIANTS))",
        "endif",
        "",
        "# ---- module name mapping -------------------------------------",
    ]

    for name in modules:
        short = name.removeprefix("epic-")
        out.append(f"EPICURUS_MODULE_{short} := {name}")
    out.append("")

    out.append("# ---- per-module data -----------------------------------------")
    for name in modules:
        mod = manifest.modules[name]
        resolved = " ".join(manifest.resolve_deps(name))
        supported = " ".join(mod.supported.get(family_name, []))
        out.append(f"EPICURUS_RESOLVED_{name} := {resolved}")
        out.append(f"EPICURUS_SUPPORTED_{name} := {supported}")
        for mcu, reason in sorted(mod.excluded.items()):
            if mcu in fam.variants:
                out.append(f"EPICURUS_WHYNOT_{name}_{mcu} := {reason}")
        own_srcs = list(mod.sources) + list(mod.sources_by_family.get(family_name, []))
        srcs = " ".join(f"$(EPICURUS_DIR)/{mod.dir}/{s}" for s in own_srcs)
        incs = " ".join(f"$(EPICURUS_DIR)/{mod.dir}/{i}" for i in mod.includes)
        out.append(f"EPICURUS_SRCS_{name} := {srcs}")
        out.append(f"EPICURUS_INCS_{name} := {incs}")
        out.append("")

    hal = " \\\n  ".join(f"$(EPICURUS_DIR)/{s}" for s in fam.hal_sources)
    out += [
        "# ---- family HAL ----------------------------------------------",
        "# The full peripheral set, not trimmed per module: the IRQ",
        "# dispatch takes strong references to every peripheral handler,",
        "# so a partial set will not link.",
        f"EPICURUS_HAL_SRCS := \\\n  {hal}",
        "",
    ]
    for cond in fam.conditional_sources:
        out.append(f"ifneq ($(filter $(EPICURUS_MCU),{' '.join(cond.variants)}),)")
        out.append(f"  EPICURUS_HAL_SRCS += $(EPICURUS_DIR)/{cond.path}")
        out.append("endif")
    out.append("")

    fam_incs = " ".join(f"-I$(EPICURUS_DIR)/{i}" for i in fam.includes)
    out += [
        "# Include order is significant: include/target must precede",
        "# include so the platform header resolves to the real-target",
        "# version, not the host memory-backed one.",
        f"EPICURUS_FAMILY_INCLUDES := {fam_incs}",
        "",
        "# ---- resolution ----------------------------------------------",
        "EPICURUS_SELECTED := $(foreach m,$(EPICURUS_MODULES),"
        "$(if $(EPICURUS_MODULE_$(m)),$(EPICURUS_MODULE_$(m)),"
        "$(error unknown Epicurus module '$(m)'; see SUPPORT.md)))",
        "",
        "EPICURUS_ALL := $(sort $(foreach m,$(EPICURUS_SELECTED),"
        "$(EPICURUS_RESOLVED_$(m))))",
        "",
        "# Every selected module must declare this part as supported.",
        "$(foreach m,$(EPICURUS_ALL),\\",
        "  $(if $(filter $(EPICURUS_MCU),$(EPICURUS_SUPPORTED_$(m))),,\\",
        "    $(error $(m) is not supported on $(EPICURUS_MCU)"
        "$(if $(EPICURUS_WHYNOT_$(m)_$(EPICURUS_MCU)),"
        " ($(EPICURUS_WHYNOT_$(m)_$(EPICURUS_MCU))),). "
        "Supported: $(if $(EPICURUS_SUPPORTED_$(m)),"
        "$(EPICURUS_SUPPORTED_$(m)),none). See SUPPORT.md.)))",
        "",
        "EPICURUS_SRCS := $(EPICURUS_HAL_SRCS) "
        "$(foreach m,$(EPICURUS_ALL),$(EPICURUS_SRCS_$(m)))",
        "EPICURUS_INCLUDES := $(EPICURUS_FAMILY_INCLUDES) "
        "$(foreach m,$(EPICURUS_ALL),$(addprefix -I,$(EPICURUS_INCS_$(m))))",
        "",
        "EPICURUS_CFLAGS := $(EPICURUS_INCLUDES) -DPIC$(EPICURUS_MCU)",
        "",
    ]
    return "\n".join(out) + "\n"


def emit_sources_json(manifest, family_name: str, version: str) -> str:
    """The same resolved data as epicurus.mk, for non-make consumers.

    MPLAB X users cannot include a .mk, and neither can someone driving
    XC8 from CMake or a shell script. MPLABX.md is generated from this,
    so its instructions cannot go stale when a source file moves.
    """
    fam = _family(manifest, family_name)
    modules = {}
    for name in modules_for_family(manifest, family_name):
        mod = manifest.modules[name]
        own_srcs = list(mod.sources) + list(mod.sources_by_family.get(family_name, []))
        example = mod.examples.get(family_name)
        modules[name] = {
            "resolved": manifest.resolve_deps(name),
            "sources": [f"{mod.dir}/{s}" for s in own_srcs],
            "includes": [f"{mod.dir}/{i}" for i in mod.includes],
            "supported": mod.supported.get(family_name, []),
            "excluded": {
                mcu: reason for mcu, reason in sorted(mod.excluded.items())
                if mcu in fam.variants
            },
            "example": None if example is None else {
                "name": example.name,
                "sources": [f"{mod.dir}/{s}" for s in example.sources],
                "config": dict(example.config),
            },
        }

    doc = {
        "version": version,
        "family": family_name,
        "dfp": fam.dfp,
        "variants": fam.variants,
        "hal_sources": fam.hal_sources,
        "conditional_sources": [
            {"path": c.path, "variants": c.variants}
            for c in fam.conditional_sources
        ],
        "family_includes": fam.includes,
        "modules": modules,
    }
    return json.dumps(doc, indent=2, sort_keys=True) + "\n"


def emit_support_md(manifest, family_name: str, version: str) -> str:
    """The per-module, per-part support table, with reasons."""
    fam = _family(manifest, family_name)
    modules = modules_for_family(manifest, family_name)

    out = [
        f"# Supported parts, Epicurus {version} ({family_name})",
        "",
        "Generated from `epic-common/manifest/modules.toml`. A `no` here",
        "is a combination that genuinely does not build, not one that is",
        "merely untested: asking for it fails immediately with the reason",
        "rather than as a wall of XC8 linker errors.",
        "",
        "| Module | " + " | ".join(fam.variants) + " |",
        "|---" * (len(fam.variants) + 1) + "|",
    ]
    for name in modules:
        mod = manifest.modules[name]
        supported = mod.supported.get(family_name, [])
        cells = ["yes" if v in supported else "no" for v in fam.variants]
        out.append(f"| `{name}` | " + " | ".join(cells) + " |")

    reasons = [
        (name, mcu, reason)
        for name in modules
        for mcu, reason in sorted(manifest.modules[name].excluded.items())
        if mcu in fam.variants
    ]
    if reasons:
        out += ["", "## Why not", "", "| Module | Part | Reason |", "|---|---|---|"]
        out += [f"| `{n}` | {m} | {r} |" for n, m, r in reasons]

    out += [
        "",
        "## Selecting modules",
        "",
        "Dependencies resolve automatically: naming `modbus` pulls in",
        "`serial` and `tick`. List only what you use directly.",
        "",
        "```make",
        "EPICURUS_MODULES := serial tick",
        "```",
        "",
    ]
    return "\n".join(out) + "\n"


def _sample_module(manifest, family_name, mcu):
    """A module that actually builds on `mcu`, for use in examples."""
    for name in modules_for_family(manifest, family_name):
        if mcu in manifest.modules[name].supported.get(family_name, []):
            return name.removeprefix("epic-")
    raise BundleError(f"no module supports {mcu}; cannot write a quickstart")


def emit_quickstart_md(manifest, family_name: str, version: str) -> str:
    fam = _family(manifest, family_name)
    mcu = fam.variants[-1]
    module = _sample_module(manifest, family_name, mcu)

    return "\n".join([
        f"# Quick start, Epicurus {version} ({family_name})",
        "",
        "You need MPLAB XC8 (`xc8-cc`) on your PATH and GNU make. No",
        "MPLAB X, no licence, no IDE.",
        "",
        "## 1. Put the bundle in your project",
        "",
        "```sh",
        "mkdir -p third_party",
        f"tar xzf epicurus-{fam.hal_dir.removesuffix('-hal')}-{version}.tar.gz \\",
        "  -C third_party",
        "mv third_party/epicurus-* third_party/epicurus",
        "```",
        "",
        "## 2. Write your Makefile",
        "",
        "```make",
        "EPICURUS_DIR := third_party/epicurus",
        f"EPICURUS_MCU := {mcu}",
        f"EPICURUS_MODULES := {module}",
        "include $(EPICURUS_DIR)/epicurus.mk",
        "",
        "# xc8-cc must be on PATH (the free MPLAB XC8 tier is enough).",
        "ifeq ($(shell command -v xc8-cc),)",
        "$(error xc8-cc not found on PATH. Add MPLAB XC8's bin/ to PATH, e.g.: \\",
        "        export PATH=$$PATH:/opt/microchip/xc8/v4.00/bin)",
        "endif",
        "# The device pack lives inside the XC8 install (installed by MPLAB",
        "# X or dropped in manually); resolve it from xc8-cc's own location.",
        "XC8_ROOT := $(patsubst %/bin/,%,$(dir $(shell command -v xc8-cc)))",
        "DFP := $(XC8_ROOT)/pic/packs/$(EPICURUS_DFP)/xc8",
        "ifeq ($(wildcard $(DFP)),)",
        "$(error device pack $(EPICURUS_DFP) not found under $(XC8_ROOT)/pic/packs; \\",
        "        install it with MPLAB X (Tools > Packs) or unzip the DFP into that directory)",
        "endif",
        "",
        "SRCS := $(EPICURUS_SRCS)",
        "BUILD := build",
        "HEX := $(BUILD)/app.hex",
        "# XC8 writes its intermediates into the working directory, so the",
        "# compile runs from inside build/ to keep the project root clean.",
        "CFLAGS := -mdfp=$(DFP) -mcpu=$(shell echo $(EPICURUS_MCU) | tr A-Z a-z) \\",
        f"          -O2 -std=c99 -Wall -Wextra $(subst -I,-I../,$(EPICURUS_CFLAGS)) -DFOSC_HZ={fam.fosc_hz}",
        "",
        "all: $(HEX)",
        "",
        "$(HEX): $(SRCS) main.c",
        "\t@mkdir -p $(BUILD)",
        "\tcd $(BUILD) && xc8-cc $(CFLAGS) $(addprefix ../,$(SRCS)) ../main.c -o app.hex -ginhx32",
        "",
        "clean:",
        "\trm -rf $(BUILD)",
        "",
        ".PHONY: all clean",
        "```",
        "",
        "## 3. Build",
        "",
        "```sh",
        "make",
        "```",
        "",
        "Program `app.hex` with MPLAB X, MPLAB IPE, or any programmer.",
        "",
        "## Notes",
        "",
        "- Module names drop the `epic-` prefix in `EPICURUS_MODULES`.",
        "- Dependencies resolve automatically: `modbus` pulls in `serial`",
        "  and `tick`.",
        "- Asking for a module on a part it does not fit fails immediately",
        "  with the reason. See `SUPPORT.md` for the full table.",
        f"- Supported parts in this bundle: {', '.join(fam.variants)}.",
        "- You still supply your own `#pragma config` words. The reference",
        "  project under `examples/` has a working set to copy.",
        "",
    ]) + "\n"


def reference_project_dir(manifest, family_name: str) -> str:
    """Where this family's reference MPLAB X project lives in the repo.

    Derived from the family's hal_dir so adding a family does not need a
    second lookup table to be kept in sync.
    """
    fam = _family(manifest, family_name)
    slug = fam.hal_dir.removesuffix("-hal")
    return f"examples/epicurus-demo-{slug}.X"


def emit_mplabx_md(manifest, family_name: str, version: str) -> str:
    """Instructions for MPLAB X and the MPLAB extension for VS Code.

    Generated from the same resolved data epicurus.mk uses, because an
    MPLAB X user cannot include a .mk and a hand-written list of folders
    would go stale the first time a source moved.
    """
    fam = _family(manifest, family_name)
    modules = modules_for_family(manifest, family_name)

    src_dirs = sorted({str(pathlib.PurePosixPath(s).parent) for s in fam.hal_sources})
    for name in modules:
        mod = manifest.modules[name]
        own_srcs = list(mod.sources) + list(mod.sources_by_family.get(family_name, []))
        src_dirs += sorted({
            f"{mod.dir}/{pathlib.PurePosixPath(s).parent}" for s in own_srcs
        })
    src_dirs = sorted(set(src_dirs))

    out = [
        f"# Using Epicurus {version} from MPLAB X ({family_name})",
        "",
        "Two ways in. The reference project is the fast one.",
        "",
        "## Option 1: open the reference project",
        "",
        "```",
        "examples/epicurus-demo.X",
        "```",
        "",
        "Open it in MPLAB X (File > Open Project), pick your part under",
        "Project Properties, and Build. Confirm it produces a `.hex`, then",
        "either build your application inside it or copy its settings into",
        "your own project using Option 2.",
        "",
        "This also works in the MPLAB extension for VS Code, which opens",
        "the same `.X` project format.",
        "",
"## Option 2: add Epicurus to an existing project",
"",
"The fastest way is to generate a `.X` with the scaffolder. From inside",
"the bundle, run `epicurus init` and answer family, part, and modules:",
"it writes a `.X` configured for your exact part + module subset, ready",
"to open in MPLAB X (or the MPLAB extension for VS Code) and Build.",
"",
"If you would rather wire an existing project by hand, the steps below",
"list every source folder and include path this bundle ships.",
"",
        "### Add the sources",
        "",
        "Right-click `Source Files` > `Add Existing Items from Folders...`,",
        "then add each of these from this bundle:",
        "",
    ]
    out += [f"- `{d}`" for d in src_dirs]
    out += [
        "",
        "Add only the module folders you actually use. The HAL folders are",
        "not optional: the interrupt dispatch takes strong references to",
        "every peripheral handler, so a partial set will not link.",
        "",
        "### Set the include paths",
        "",
        "Project Properties > XC8 Compiler > Include directories, in this",
        "order (the order matters: `include/target` must come first so the",
        "platform header resolves to the real-target version rather than",
        "the host one):",
        "",
    ]
    out += [f"{i + 1}. `{inc}`" for i, inc in enumerate(fam.includes)]
    for name in modules:
        mod = manifest.modules[name]
        for inc in mod.includes:
            out.append(f"   plus `{mod.dir}/{inc}` if you use `{name}`")
    out += [
        "",
        "### Set the device pack",
        "",
        f"This family needs the `{fam.dfp}` pack. Install it through MPLAB",
        "X's Tools > Packs manager if the part does not appear in the",
        "device list.",
        "",
        "### Define the part macro",
        "",
        "Project Properties > XC8 Compiler > Preprocessor macros, add",
        "`PIC<part>`, for example `PIC" + fam.variants[-1] + "`.",
        "",
        "## Which parts work",
        "",
        "See `SUPPORT.md`. MPLAB X will not warn you about an unsupported",
        "combination the way `epicurus.mk` does; it will fail at link time",
        "with an XC8 memory error instead.",
        "",
    ]
    return "\n".join(out) + "\n"


def emit_parts_map(manifest) -> str:
    """One 'part family-slug' line per supported part.

    Shipped as the release asset install.sh downloads to pick the right
    bundle when the user passes a part instead of a family. Derived from
    the manifest so it cannot drift from the bundles it describes."""
    out = []
    for name in sorted(manifest.families):
        fam = manifest.families[name]
        slug = fam.hal_dir.removesuffix("-hal")
        for variant in fam.variants:
            out.append(f"{variant} {slug}")
    return "\n".join(out) + "\n"
