#!/usr/bin/env python3
"""Generate a self-contained, per-family source bundle.

A bundle is what someone outside this repo actually consumes: one
family's HAL, epic-common, every module that builds on that family, and
a set of generated files that tell their build system what to compile.

Module dependencies are flattened here, at generation time, so the
emitted epicurus.mk is a table of precomputed variables plus a guard.
Recursive dependency resolution in GNU make is possible and unpleasant;
doing it in Python and emitting the answer is neither.

See docs/superpowers/specs/2026-08-05-distribution-design.md.
"""
from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import epicmanifest  # noqa: E402


class BundleError(Exception):
    """A bundle that cannot be generated as asked."""


def _family(manifest, family_name):
    fam = manifest.families.get(family_name)
    if fam is None:
        known = ", ".join(sorted(manifest.families))
        raise BundleError(f"unknown family '{family_name}'; known: {known}")
    return fam


def modules_for_family(manifest, family_name: str) -> list[str]:
    """Every module with at least one supported part in this family.

    Excludes a module whose dir equals the family's own hal_dir: that
    shape (epic-pic16f193x-firmware in the real manifest) is CI-coverage
    plumbing for a family with no real modules yet, plan 1's manifest-
    equivalence stand-in for the family's bare-HAL build, not a library
    a bundle consumer would ever ask for by name. Excluding it is what
    keeps PIC16F193X a genuine HAL-only bundle.
    """
    fam = _family(manifest, family_name)
    return sorted(
        name for name, mod in manifest.modules.items()
        if mod.supported.get(family_name) and mod.dir != fam.hal_dir
    )


def files_for_family(manifest, family_name: str) -> list[str]:
    """Every repo-root-relative file the bundle must copy.

    Sources only. Documentation and headers are copied wholesale by
    make_bundle.py's directory walk; this is the list that has to be
    exactly right because it is what the emitted epicurus.mk names.
    """
    fam = _family(manifest, family_name)
    files = set(fam.hal_sources)
    files |= {c.path for c in fam.conditional_sources}

    for name in modules_for_family(manifest, family_name):
        mod = manifest.modules[name]
        files |= {f"{mod.dir}/{s}" for s in mod.sources}
        files |= {f"{mod.dir}/{s}" for s in mod.sources_by_family.get(family_name, [])}
        example = mod.examples.get(family_name)
        if example is not None:
            files |= {f"{mod.dir}/{s}" for s in example.sources}

    return sorted(files)


def emit_epicurus_mk(manifest, family_name: str, version: str) -> str:
    """The consumer-facing make fragment.

    Data plus a guard, no build rules: the consumer's own Makefile owns
    the rules, and this file must not assume anything about them beyond
    the ability to `include` it. Dependency resolution is already done
    (see EPICURUS_RESOLVED_*), so nothing here recurses.
    """
    fam = _family(manifest, family_name)
    modules = modules_for_family(manifest, family_name)

    out = [
        "# GENERATED by scripts/bundlegen.py. Do not edit.",
        f"# Epicurus {version}, {family_name} family.",
        "#",
        "# Usage from your own Makefile:",
        "#",
        "#   EPICURUS_DIR := third_party/epicurus",
        "#   EPICURUS_MCU := 16F877A",
        "#   EPICURUS_MODULES := serial tick",
        "#   include $(EPICURUS_DIR)/epicurus.mk",
        "#",
        "#   SRCS := main.c $(EPICURUS_SRCS)",
        "#   CFLAGS += $(EPICURUS_CFLAGS)",
        "#",
        "# Sets EPICURUS_SRCS, EPICURUS_INCLUDES, and EPICURUS_CFLAGS.",
        "# Module names are given without the epic- prefix.",
        "",
        f"EPICURUS_VERSION := {version}",
        f"EPICURUS_FAMILY  := {family_name}",
        f"EPICURUS_DFP     := {fam.dfp}",
        f"EPICURUS_VARIANTS := {' '.join(fam.variants)}",
        "",
        "ifeq ($(strip $(EPICURUS_DIR)),)",
        "  $(error EPICURUS_DIR is not set: point it at this bundle's root)",
        "endif",
        "ifeq ($(strip $(EPICURUS_MCU)),)",
        "  $(error EPICURUS_MCU is not set: choose one of $(EPICURUS_VARIANTS))",
        "endif",
        "",
        "# ---- module name mapping -------------------------------------",
    ]

    for name in modules:
        short = name.removeprefix("epic-")
        out.append(f"EPICURUS_MODULE_{short} := {name}")
    out.append("")

    out.append("# ---- per-module data -----------------------------------------")
    for name in modules:
        mod = manifest.modules[name]
        resolved = " ".join(manifest.resolve_deps(name))
        supported = " ".join(mod.supported.get(family_name, []))
        out.append(f"EPICURUS_RESOLVED_{name} := {resolved}")
        out.append(f"EPICURUS_SUPPORTED_{name} := {supported}")
        for mcu, reason in sorted(mod.excluded.items()):
            if mcu in fam.variants:
                out.append(f"EPICURUS_WHYNOT_{name}_{mcu} := {reason}")
        own_srcs = list(mod.sources) + list(mod.sources_by_family.get(family_name, []))
        srcs = " ".join(f"$(EPICURUS_DIR)/{mod.dir}/{s}" for s in own_srcs)
        incs = " ".join(f"$(EPICURUS_DIR)/{mod.dir}/{i}" for i in mod.includes)
        out.append(f"EPICURUS_SRCS_{name} := {srcs}")
        out.append(f"EPICURUS_INCS_{name} := {incs}")
        out.append("")

    hal = " \\\n  ".join(f"$(EPICURUS_DIR)/{s}" for s in fam.hal_sources)
    out += [
        "# ---- family HAL ----------------------------------------------",
        "# The full peripheral set, not trimmed per module: the IRQ",
        "# dispatch takes strong references to every peripheral handler,",
        "# so a partial set will not link.",
        f"EPICURUS_HAL_SRCS := \\\n  {hal}",
        "",
    ]
    for cond in fam.conditional_sources:
        out.append(f"ifneq ($(filter $(EPICURUS_MCU),{' '.join(cond.variants)}),)")
        out.append(f"  EPICURUS_HAL_SRCS += $(EPICURUS_DIR)/{cond.path}")
        out.append("endif")
    out.append("")

    fam_incs = " ".join(f"-I$(EPICURUS_DIR)/{i}" for i in fam.includes)
    out += [
        "# Include order is significant: include/target must precede",
        "# include so the platform header resolves to the real-target",
        "# version, not the host memory-backed one.",
        f"EPICURUS_FAMILY_INCLUDES := {fam_incs}",
        "",
        "# ---- resolution ----------------------------------------------",
        "EPICURUS_SELECTED := $(foreach m,$(EPICURUS_MODULES),"
        "$(if $(EPICURUS_MODULE_$(m)),$(EPICURUS_MODULE_$(m)),"
        "$(error unknown Epicurus module '$(m)'; see SUPPORT.md)))",
        "",
        "EPICURUS_ALL := $(sort $(foreach m,$(EPICURUS_SELECTED),"
        "$(EPICURUS_RESOLVED_$(m))))",
        "",
        "# Every selected module must declare this part as supported.",
        "$(foreach m,$(EPICURUS_ALL),\\",
        "  $(if $(filter $(EPICURUS_MCU),$(EPICURUS_SUPPORTED_$(m))),,\\",
        "    $(error $(m) is not supported on $(EPICURUS_MCU)"
        "$(if $(EPICURUS_WHYNOT_$(m)_$(EPICURUS_MCU)),"
        " ($(EPICURUS_WHYNOT_$(m)_$(EPICURUS_MCU))),). "
        "Supported: $(if $(EPICURUS_SUPPORTED_$(m)),"
        "$(EPICURUS_SUPPORTED_$(m)),none). See SUPPORT.md.)))",
        "",
        "EPICURUS_SRCS := $(EPICURUS_HAL_SRCS) "
        "$(foreach m,$(EPICURUS_ALL),$(EPICURUS_SRCS_$(m)))",
        "EPICURUS_INCLUDES := $(EPICURUS_FAMILY_INCLUDES) "
        "$(foreach m,$(EPICURUS_ALL),-I$(EPICURUS_INCS_$(m)))",
        "",
        "EPICURUS_CFLAGS := $(EPICURUS_INCLUDES) -DPIC$(EPICURUS_MCU)",
        "",
    ]
    return "\n".join(out) + "\n"


def emit_sources_json(manifest, family_name: str, version: str) -> str:
    """The same resolved data as epicurus.mk, for non-make consumers.

    MPLAB X users cannot include a .mk, and neither can someone driving
    XC8 from CMake or a shell script. MPLABX.md is generated from this,
    so its instructions cannot go stale when a source file moves.
    """
    fam = _family(manifest, family_name)
    modules = {}
    for name in modules_for_family(manifest, family_name):
        mod = manifest.modules[name]
        own_srcs = list(mod.sources) + list(mod.sources_by_family.get(family_name, []))
        example = mod.examples.get(family_name)
        modules[name] = {
            "resolved": manifest.resolve_deps(name),
            "sources": [f"{mod.dir}/{s}" for s in own_srcs],
            "includes": [f"{mod.dir}/{i}" for i in mod.includes],
            "supported": mod.supported.get(family_name, []),
            "excluded": {
                mcu: reason for mcu, reason in sorted(mod.excluded.items())
                if mcu in fam.variants
            },
            "example": None if example is None else {
                "name": example.name,
                "sources": [f"{mod.dir}/{s}" for s in example.sources],
                "config": dict(example.config),
            },
        }

    doc = {
        "version": version,
        "family": family_name,
        "dfp": fam.dfp,
        "variants": fam.variants,
        "hal_sources": fam.hal_sources,
        "conditional_sources": [
            {"path": c.path, "variants": c.variants}
            for c in fam.conditional_sources
        ],
        "family_includes": fam.includes,
        "modules": modules,
    }
    return json.dumps(doc, indent=2, sort_keys=True) + "\n"


def emit_support_md(manifest, family_name: str, version: str) -> str:
    """The per-module, per-part support table, with reasons."""
    fam = _family(manifest, family_name)
    modules = modules_for_family(manifest, family_name)

    out = [
        f"# Supported parts, Epicurus {version} ({family_name})",
        "",
        "Generated from `epic-common/manifest/modules.toml`. A `no` here",
        "is a combination that genuinely does not build, not one that is",
        "merely untested: asking for it fails immediately with the reason",
        "rather than as a wall of XC8 linker errors.",
        "",
        "| Module | " + " | ".join(fam.variants) + " |",
        "|---" * (len(fam.variants) + 1) + "|",
    ]
    for name in modules:
        mod = manifest.modules[name]
        supported = mod.supported.get(family_name, [])
        cells = ["yes" if v in supported else "no" for v in fam.variants]
        out.append(f"| `{name}` | " + " | ".join(cells) + " |")

    reasons = [
        (name, mcu, reason)
        for name in modules
        for mcu, reason in sorted(manifest.modules[name].excluded.items())
        if mcu in fam.variants
    ]
    if reasons:
        out += ["", "## Why not", "", "| Module | Part | Reason |", "|---|---|---|"]
        out += [f"| `{n}` | {m} | {r} |" for n, m, r in reasons]

    out += [
        "",
        "## Selecting modules",
        "",
        "Dependencies resolve automatically: naming `modbus` pulls in",
        "`serial` and `tick`. List only what you use directly.",
        "",
        "```make",
        "EPICURUS_MODULES := serial tick",
        "```",
        "",
    ]
    return "\n".join(out) + "\n"
