# scripts/epic_hal_init.py
"""Project scaffolder for Epic HAL: manifest in, ready main.c + Makefile +
patched MPLAB X .X out. Pure helpers here; scripts/epic_hal.py is the CLI."""
from __future__ import annotations
import os
import pathlib
import shutil
import xml.etree.ElementTree as ET
import bundlegen, epicmanifest


class SelectionError(Exception):
    """A (family, part, module) selection the manifest says does not build."""


def hal_pseudo_module(manifest: epicmanifest.Manifest, fam: epicmanifest.Family) -> str:
    """The family's bare-HAL 'pseudo-module' (dir == hal_dir): the module
    whose example carries the working #pragma config set for the family."""
    for name, mod in manifest.modules.items():
        if mod.dir == fam.hal_dir:
            return name
    raise SelectionError(f"no HAL pseudo-module for {fam.name} (dir={fam.hal_dir})")


def normalize_part(part: str) -> str:
    """Canonicalize a user-supplied part token: uppercase, drop a PIC/p
    prefix (16f877a, pic16f877a, p16f877a, PIC16F877A -> 16F877A)."""
    norm = part.upper()
    if norm.startswith("PIC"):
        norm = norm[3:]
    elif norm.startswith("P"):
        norm = norm[1:]
    return norm


def family_for_part(manifest: epicmanifest.Manifest, part: str) -> str | None:
    """The manifest family name that owns `part` (any case, PIC/p prefix
    tolerated), or None if unknown."""
    norm = normalize_part(part)
    for fam in manifest.families.values():
        if norm in fam.variants:
            return fam.name
    return None


def resolve_selection(manifest, family_name, part, modules) -> list[str]:
    """Expand `modules` to an ordered, deduped (selected + deps) list,
    refusing any module unsupported on `part` with the manifest's reason."""
    if family_name not in manifest.families:
        raise SelectionError(f"unknown family {family_name!r}; "
                             f"known: {', '.join(sorted(manifest.families))}")
    fam = manifest.families[family_name]
    if part not in fam.variants:
        raise SelectionError(f"{part} is not a {family_name} part; "
                             f"known: {', '.join(fam.variants)}")
    known = set(bundlegen.modules_for_family(manifest, family_name))
    known.add(hal_pseudo_module(manifest, fam))
    ordered: list[str] = []
    seen: set[str] = set()
    for m in modules:
        if m not in known:
            raise SelectionError(f"unknown module {m!r} for {family_name}")
        for name in manifest.resolve_deps(m):
            if name in seen:
                continue
            if not manifest.is_supported(name, family_name, part):
                reason = manifest.exclusion_reason(name, part) or ""
                sup = manifest.modules[name].supported.get(family_name, [])
                raise SelectionError(
                    f"{name} is not supported on {part}"
                    + (f" ({reason})" if reason else "")
                    + f". Supported on {family_name}: {', '.join(sup) or 'none'}.")
            seen.add(name)
            ordered.append(name)
    return ordered


def emit_makefile(manifest, family_name, part, modules, bundle_dir, name) -> str:
    """The QUICKSTART.md six-line form, filled. `modules` are short names
    (epic- prefix dropped, as EPIC_HAL_MODULES expects)."""
    fam = manifest.families[family_name]
    mods = " ".join(modules)
    return "\n".join([
        f"# Generated by epic-hal init. Edit freely.",
        f"EPIC_HAL_DIR := {bundle_dir}",
        f"EPIC_HAL_MCU := {part}",
        f"EPIC_HAL_MODULES := {mods}",
        f"include $(EPIC_HAL_DIR)/epic-hal.mk",
        "",
        "# Toolchain: xc8 (default, needs Microchip pack) or epic-cc (no pack).",
        "# `make TOOLCHAIN=epic-cc` builds the same sources with epic-cc.",
        "TOOLCHAIN ?= xc8",
        "",
        "# xc8-cc must be on PATH for the xc8 path; epic-cc for the epic-cc path.",
        "ifeq ($(TOOLCHAIN),epic-cc)",
        "ifeq ($(shell command -v epic-cc),)",
        "$(error epic-cc not found on PATH. Build it from github.com/apojomovsky/epic-cc: cargo build --bin epic-cc)",
        "endif",
        "else",
        "ifeq ($(shell command -v xc8-cc),)",
        "$(error xc8-cc not found on PATH. Add MPLAB XC8's bin/ to PATH, e.g.: \\",
        "        export PATH=$$PATH:/opt/microchip/xc8/v4.00/bin)",
        "endif",
        "endif",
        "# The device pack lives inside the XC8 install (installed by MPLAB",
        "# X or dropped in manually); resolve it from xc8-cc's own location",
        "# rather than assuming a version or install path.",
        "XC8_ROOT := $(patsubst %/bin/,%,$(dir $(shell command -v xc8-cc)))",
        "DFP := $(XC8_ROOT)/pic/packs/$(EPIC_HAL_DFP)/xc8",
        "ifeq ($(TOOLCHAIN),xc8)",
        "ifeq ($(wildcard $(DFP)),)",
        "$(error device pack $(EPIC_HAL_DFP) not found under $(XC8_ROOT)/pic/packs. \\",
        "        Install it with MPLAB X (Tools > Packs) or unzip the downloaded DFP into that directory)",
        "endif",
        "endif",
        "",
        "SRCS := $(EPIC_HAL_SRCS)",
        "BUILD := $(EPIC_HAL_BUILD_DIR)",
        f"HEX := $(BUILD)/{name}.hex",
        "",
        "# XC8 writes its intermediates (.p1, .d, .o) into the working",
        "# directory, so the compile runs from inside build/ to keep the",
        "# project root clean; the bundle-relative include and source",
        "# paths get a ../ prefix for that.",
        "# The -Wno-* list silences library-and-small-app noise: the full",
        "# HAL is linked, so most peripheral APIs are never called (520,",
        "# 2053, -Wunused-function), the optional-callback seams call via",
        "# a NULL pointer (2098, 759), and the compiler duplicates a",
        "# non-reentrant helper (1510). Warning 1393 (hardware stack",
        "# overflow) is deliberately NOT silenced: it is a real risk.",
        "ifeq ($(TOOLCHAIN),epic-cc)",
        "CFLAGS := -I../$(EPIC_HAL_DIR)/include/epiccc $(subst -I,-I../,$(EPIC_HAL_CFLAGS)) -DFOSC_HZ={fam.fosc_hz} -D__EPIC_CC__ \\",
        "          -Wno-unused-function",
        "else",
        "CFLAGS := -mdfp=$(DFP) -mcpu=$(shell echo $(EPIC_HAL_MCU) | tr A-Z a-z) \\",
        f"          -O2 -std=c99 -Wall -Wextra $(subst -I,-I../,$(EPIC_HAL_CFLAGS)) -DFOSC_HZ={fam.fosc_hz} \\",
        "          -Wno-520 -Wno-2053 -Wno-2098 -Wno-759 -Wno-1510 -Wno-unused-function",
        "endif",
        "",
        "all: $(HEX)",
        "",
        "$(HEX): $(SRCS) main.c",
        "\t@mkdir -p $(BUILD)",
        "ifeq ($(TOOLCHAIN),epic-cc)",
        f"\tepic-cc --device $(shell echo $(EPIC_HAL_MCU) | tr A-Z a-z | sed 's/^/p/') $(CFLAGS) -o $(HEX) $(SRCS) main.c",
        "else",
        f"\tcd $(BUILD) && xc8-cc $(CFLAGS) $(addprefix ../,$(SRCS)) ../main.c -o {name}.hex -ginhx32",
        "endif",
        "",
        "clean:",
        "\trm -rf $(BUILD) build",
        "",
        ".PHONY: all clean",
        "",
    ])
def _gpio_header(fam) -> str:
    """The family GPIO header path, e.g. peripherals/pic16f87xa_gpio.h."""
    base = fam.hal_dir.removesuffix("-hal")
    return f"peripherals/{base}_gpio.h"


def emit_main_c(manifest, family_name, part, modules) -> str:
    """A buildable main.c skeleton picked from the selected modules (short
    names): tick-blink when tick is selected, serial-echo when serial is
    selected, else a bare HAL GPIO blink. The family's working #pragma
    config always comes from the family pseudo-module's example, so the
    same source shape builds on all three families; only the GPIO header
    name and the skeleton body are family/module-specific."""
    fam = manifest.families[family_name]
    pseudo = hal_pseudo_module(manifest, fam)
    example = manifest.example_for(pseudo, family_name, part)
    pragmas = example.config if example is not None else {}
    header = "/* Generated by epic-hal init. Edit freely. */"
    pragma_lines = [f"#pragma config {k} = {v}" for k, v in pragmas.items()]

    if "tick" in modules:
        lines = [
            header,
            "#include <xc.h>",
            '#include "epic_tick.h"',
            f'#include "{_gpio_header(fam)}"',
            "",
        ]
        lines += pragma_lines
        lines += [
            "",
            "int main(void)",
            "{",
            "    EPIC_GPIO_Init(GPIOB, GPIO_PIN_0, GPIO_MODE_OUTPUT);",
            "    epic_tick_init(FOSC_HZ);",
            "",
            "    uint32_t last = epic_tick_get();",
            "    for (;;) {",
            "        if ((epic_tick_get() - last) >= 500u) {",
            "            last = epic_tick_get();",
            "            EPIC_GPIO_TogglePin(GPIOB, GPIO_PIN_0);",
            "        }",
            "    }",
            "}",
            "",
        ]
        return "\n".join(lines)

    if "serial" in modules:
        lines = [
            header,
            "#include <xc.h>",
            '#include "epic_serial.h"',
            "",
        ]
        lines += pragma_lines
        lines += [
            "",
            "int main(void)",
            "{",
            "    epic_serial_init(FOSC_HZ, 115200u);",
            "    uint8_t buf[16];",
            "    for (;;) {",
            "        int n = epic_serial_read(buf, sizeof buf);",
            "        if (n > 0) epic_serial_write(buf, n);",
            "    }",
            "}",
            "",
        ]
        return "\n".join(lines)

    lines = [
        header,
        "#include <xc.h>",
        f'#include "{_gpio_header(fam)}"',
        "",
    ]
    lines += pragma_lines
    lines += [
        "",
        "int main(void)",
        "{",
        "    EPIC_GPIO_Init(GPIOB, GPIO_PIN_0, GPIO_MODE_OUTPUT);",
        "    for (;;) {",
        "        EPIC_GPIO_TogglePin(GPIOB, GPIO_PIN_0);",
        "        for (volatile uint32_t i = 0; i < 100000u; i++) {",
        "        }",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def source_dirs(manifest, fam, part, selected) -> list[str]:
    """Repo-root-relative source directories: HAL (always full) + each
    resolved module's library source dirs. sourceRootList is directories,
    not files, so we collapse each source to its parent."""
    dirs: set[str] = set()
    for s in fam.hal_sources:
        dirs.add(str(pathlib.PurePosixPath(s).parent))
    for c in fam.conditional_sources:
        if part in c.variants:
            dirs.add(str(pathlib.PurePosixPath(c.path).parent))
    names: set[str] = set()
    for m in selected:
        names.update(manifest.resolve_deps(m))
    for name in names:
        mod = manifest.modules[name]
        for s in list(mod.sources) + list(mod.sources_by_family.get(fam.name, [])):
            dirs.add(f"{mod.dir}/{pathlib.PurePosixPath(s).parent}")
    return sorted(dirs)


def include_dirs(manifest, fam, part, selected) -> list[str]:
    """Family includes first (include/target before include, load-bearing),
    then each resolved module's includes, deduped."""
    out: list[str] = []
    seen: set[str] = set()
    for m in selected:
        for inc in manifest.includes_for(m, part):
            if inc not in seen:
                seen.add(inc)
                out.append(inc)
    return out


def patch_configurations_xml(xml_text, fam, part, selected_dirs, include_dirs,
                             prefix="../..") -> str:
    """Patch the four per-(part, subset) fields of a family's reference
    configurations.xml. `prefix` is the path from the .X directory to the
    bundle root (init_project computes it; ../.. keeps the nested layout
    unchanged). ElementTree reformats the file; MPLAB X rewrites it on
    open, so formatting drift is harmless and the CI headless build gate
    proves the result still opens and builds."""
    root = ET.fromstring(xml_text)
    root.find(".//targetDevice").text = f"PIC{part}"
    for prop in root.findall(".//property[@key='define-macros']"):
        prop.set("value", f"PIC{part};FOSC_HZ={fam.fosc_hz}")
    inc_value = ";".join(f"{prefix}/{i}" for i in include_dirs)
    for prop in root.findall(".//property[@key='extra-include-directories']"):
        prop.set("value", inc_value)
    sr = root.find(".//sourceRootList")
    for elem in list(sr):
        sr.remove(elem)
    for d in selected_dirs:
        ET.SubElement(sr, "Elem").text = f"{prefix}/{d}"
    return ET.tostring(root, encoding="UTF-8", xml_declaration=True).decode()


def _reference_x_dir(manifest, fam, bundle_dir) -> pathlib.Path:
    """Locate the family reference MPLAB X project under bundle_dir/examples.
    A generated bundle uses examples/epic-hal-demo.X; a repo checkout uses
    examples/epic-hal-demo-<slug>.X (see bundlegen.reference_project_dir)."""
    bundle = pathlib.Path(bundle_dir)
    bundle_form = bundle / "examples" / "epic-hal-demo.X"
    if bundle_form.is_dir():
        return bundle_form
    repo_form = bundle / bundlegen.reference_project_dir(manifest, fam.name)
    if repo_form.is_dir():
        return repo_form
    raise SelectionError(f"no reference MPLAB X project found under {bundle}/examples")


def init_project(manifest, family_name, part, modules, bundle_dir, out_dir, name) -> dict:
    """Scaffold a complete project into out_dir/<name>.X + main.c + Makefile.
    Non-destructive: refuses an existing <name>.X. Every path in the
    scaffold is the real relative path from the artifact to the bundle
    root: the .X's sourceRootList/include entries get the computed prefix
    (so the project works in place with the bundle vendored alongside,
    e.g. third_party/epic-hal), and the Makefile's EPIC_HAL_DIR is the
    same relpath. The bundle must stay where it was when the paths were
    computed, like any MPLAB X project."""
    fam = manifest.families[family_name]
    selected = resolve_selection(manifest, family_name, part, modules)
    short = [m.removeprefix("epic-") for m in modules]
    out = pathlib.Path(out_dir)
    x_dst = out / f"{name}.X"
    if x_dst.exists():
        raise FileExistsError(f"{x_dst} already exists; refusing to overwrite")
    out.mkdir(parents=True, exist_ok=True)

    src_x = _reference_x_dir(manifest, fam, bundle_dir)
    shutil.copytree(src_x, x_dst)

    sd = source_dirs(manifest, fam, part, selected)
    idd = include_dirs(manifest, fam, part, selected)
    bundle_resolved = pathlib.Path(bundle_dir).resolve()
    prefix = os.path.relpath(bundle_resolved, x_dst.resolve())
    cfg_path = x_dst / "nbproject" / "configurations.xml"
    cfg_path.write_text(patch_configurations_xml(
        cfg_path.read_text(), fam, part, sd, idd, prefix))

    main_c = emit_main_c(manifest, family_name, part, short)
    (out / "main.c").write_text(main_c)
    (x_dst / "main.c").write_text(main_c)  # so the .X opens with the user's code
    out_resolved = out.resolve()
    epic_hal_dir = os.path.relpath(bundle_resolved, out_resolved)
    (out / "Makefile").write_text(
        emit_makefile(manifest, family_name, part, short, epic_hal_dir, name))
    (out / ".gitignore").write_text("build/\n")
    return {"main_c": str(out / "main.c"),
            "makefile": str(out / "Makefile"),
            "x": str(x_dst)}
