#!/usr/bin/env python3
"""Real-target build driver: manifest in, xc8-cc build script out. Called by
CI's emit steps, scripts/ci-local-emit.py, and scripts/sim-test-local.sh.
Resolution runs wherever python3 exists; execution is a plain sh script
because the toolchain container deliberately has no python3.

Usage: epic_build.py build|matrix|report (see --help).
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import epicmanifest  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]


class UnsupportedError(Exception):
    """A (module, MCU) pair the manifest says does not build."""


def _check_supported(manifest, module, mcu):
    fam = manifest.family_of(mcu)
    if manifest.is_supported(module, fam.name, mcu):
        _check_example_deps_supported(manifest, module, fam.name, mcu)
        return fam
    reason = manifest.exclusion_reason(module, mcu)
    supported = manifest.modules[module].supported.get(fam.name, [])
    detail = ", ".join(supported) if supported else "none"
    raise UnsupportedError(
        f"{module} is not supported on {mcu}"
        + (f" ({reason})" if reason else "")
        + f". Supported on {fam.name}: {detail}."
    )


def _check_example_deps_supported(manifest, module, fam_name, mcu):
    """Fail loudly when a resolved example dep is excluded on this MCU.

    sources_for would otherwise compile the dep's sources on a part
    where the dep is excluded (the serial/tick RAM exclusions), silently
    over-building instead of surfacing the manifest gap. Module-level
    depends_on is untouched: those deps are the library's own and were
    already validated when the manifest was written.
    """
    example = manifest.example_for(module, fam_name, mcu)
    if example is None or not example.depends_on:
        return
    for dep in example.depends_on:
        if manifest.is_supported(dep, fam_name, mcu):
            continue
        reason = manifest.exclusion_reason(dep, mcu)
        supported = manifest.modules[dep].supported.get(fam_name, [])
        detail = ", ".join(supported) if supported else "none"
        raise UnsupportedError(
            f"{module}'s example on {mcu} depends on {dep}, which is "
            f"not supported there"
            + (f" ({reason})" if reason else "")
            + f". Supported on {fam_name}: {detail}."
        )


def _example_name_and_config(manifest, module, mcu, variant):
    """The (name, config-pragmas) pair for this build, honouring variant.

    variant="sim" uses the sim variant's own name and config (a full
    override, see epicmanifest.SimVariant), and raises if the requested
    (module, family) has no sim variant, the same "fail loudly" posture
    as an unsupported (module, MCU) pair.
    """
    fam = manifest.family_of(mcu)
    example = manifest.example_for(module, fam.name, mcu)
    if variant == "sim":
        sim = manifest.sim_variant_for(module, fam.name)
        if sim is None:
            raise UnsupportedError(f"{module} has no sim variant for {fam.name}")
        return sim.name, sim.config
    return (example.name, example.config) if example is not None else (None, {})


def emit_config_source(manifest, module, mcu, variant="target", toolchain="xc8",
                       fosc_hz=None):
    """The #pragma config / EPIC_CONFIG translation unit, from manifest data.

    For ``toolchain="xc8"`` this is the existing ``#pragma config`` TU
    (or ``None`` when the example has no config at all).  For
    ``toolchain="epic-cc"`` it is an ``EPIC_CONFIG("...")`` TU that
    epic-cc compiles via clang, including an explicit ``xtal_hz`` so the
    driver can derive ``EPIC_FOSC_HZ`` without an extra CLI flag.
    """
    fam = manifest.family_of(mcu)
    _, pragmas = _example_name_and_config(manifest, module, mcu, variant)
    if not pragmas:
        return None
    if toolchain == "epic-cc":
        spec = _epic_config_spec(manifest, module, mcu, variant, fosc_hz)
        if spec is None:
            return None
        # The epic-cc header provides EPIC_CONFIG; the TU must be a real
        # translation unit so the section-tagged dummy symbol survives.
        return (
            "/* Auto-generated by scripts/epic_build.py. Do not edit. */\n"
            '#include "epic-cc.h"\n'
            f'EPIC_CONFIG("{spec}");\n'
        )
    lines = [
        "/* Auto-generated by scripts/epic_build.py. Do not edit. */",
        "#include <xc.h>",
    ]
    lines += [f"#pragma config {key} = {value}" for key, value in pragmas.items()]
    return "\n".join(lines) + "\n"


def emit_build_script(manifest, module, mcu, build_dir, dfp_dir, fosc_hz=None,
                      variant="target", toolchain="xc8", epic_cc="epic-cc") -> str:
    """A self-contained POSIX sh script that produces the .hex.

    ``toolchain="xc8"`` reproduces the existing xc8-cc script (the byte-
    identical migration gate).  ``toolchain="epic-cc"`` emits a single
    ``epic-cc --target <mcu>`` invocation with the family's
    ``epiccc_sources`` slice (HAL-3: the epic-cc conformant subset,
    see the manifest README), no DFP, and a distinct build dir (caller
    decides the dir name).  No device-pack download or ``/opt/microchip``
    path is referenced on the epic-cc path.

    Flag order reproduces the Makefiles this replaces exactly (DFP, then
    -mcpu, then optimisation and warnings, then the part define, then
    includes, then FOSC_HZ). Byte-identical .hex output is the migration
    gate, and XC8's output is sensitive to command-line order, so this
    ordering is load-bearing, not cosmetic.

    fosc_hz defaults to the family's own value (a required manifest key,
    family-uniform); pass a value to override for a different crystal.

    variant="sim" builds the HARNESS=sim diagnostic firmware sim-tests.yml
    drives under MPLAB SIM instead of the real-target HARNESS=target
    build: a different harness source (spliced into sources_for at the
    swapped-out entry's position), a full config override, and a
    variant-specific .hex basename so the two builds never collide in
    the same build dir.
    """
    fam = _check_supported(manifest, module, mcu)
    example = manifest.example_for(module, fam.name, mcu)
    if example is None:
        raise UnsupportedError(f"{module} has no example for {fam.name} to build")
    if variant == "sim" and manifest.sim_variant_for(module, fam.name) is None:
        raise UnsupportedError(f"{module} has no sim variant for {fam.name}")
    if fosc_hz is None:
        fosc_hz = fam.fosc_hz

    sources = manifest.sources_for(module, mcu, variant=variant,
                                   toolchain=toolchain)
    # Epic-cc drivers: every module with a target_sizecheck_epiccc.c uses it
    # on the epic-cc path (real module logic where the compiler supports it,
    # a footprint probe where a filed isel gap remains). XC8 keeps the full
    # example.
    if toolchain == "epic-cc" and module in ("epic-fsm", "epic-pid", "epic-encoder", "epic-debounce", "epic-bus", "epic-lcd", "epic-mcp23x17", "epic-adcfilter") and variant == "target":
        mod = manifest.modules[module]
        sizecheck = f"{mod.dir}/mcu/target_sizecheck_epiccc.c"
        example = manifest.example_for(module, fam.name, mcu)
        if example is not None:
            ex_srcs = {f"{mod.dir}/{s}" for s in example.sources}
            if example.variants and mcu in example.variants:
                ex_srcs = {f"{mod.dir}/{s}" for s in example.variants[mcu].sources}
            sources = [s for s in sources if s not in ex_srcs]
            if sizecheck not in sources:
                sources.append(sizecheck)
        # Pure-logic drivers (fsm/pid/encoder/debounce) and the HAL-free
        # lcd/adcfilter drop the HAL slice; bus/mcp23x17 keep it (GPIO+SSP).
        if module in ("epic-fsm", "epic-pid", "epic-encoder", "epic-debounce", "epic-lcd", "epic-adcfilter"):
            sources = [s for s in sources if not s.startswith("pic16f") and not s.startswith("pic18") and "pic16f193x" not in s and "epic-common/src/core/epic_harness" not in s]
        # Drop tick/serial/math (the example's deps): timer2/usart isel is
        # #86's domain, and the pic16 math asm backend needs XC8's xc.h.
        sources = [s for s in sources if "epic-tick" not in s and "epic-serial" not in s and "epic-math" not in s]
        # pid.c calls epic_math_mul_s16 for real now; link the host C-path
        # implementation (the portable oracle), not the pic16 asm backend.
        if module == "epic-pid":
            sources.append("epic-math/src/host/epic_math_mul.c")
    includes = manifest.includes_for(module, mcu)
    # Drop tick/serial includes the full example pulls (they need
    # timer2/usart isel, #86's domain). Encoder/debounce keep the tick
    # header for compilation; pid keeps the epic-math header (pid.c
    # includes it; the math SOURCES are handled above).
    if toolchain == "epic-cc" and module in ("epic-fsm", "epic-pid") and variant == "target":
        includes = [i for i in includes if "epic-tick" not in i and "epic-serial" not in i]
    # HAL-3d drivers: drop tick/serial includes the example pulls.
    if toolchain == "epic-cc" and module in ("epic-bus", "epic-lcd", "epic-mcp23x17", "epic-adcfilter") and variant == "target":
        includes = [i for i in includes if "epic-tick" not in i and "epic-serial" not in i]
    objdir = f"{build_dir}/{mcu}"

    if toolchain == "epic-cc":
        # The family's epiccc_sources slice is already the epic-cc
        # conformant set (HAL-3): shared peripherals/core plus the
        # toolchain-specific vector/dispatch/WDT files. No source
        # mapping runs, only the include-dir swap (include/target ->
        # include/epiccc).
        includes = [_epiccc_include(i) for i in includes]
        # Epic-cc path: one invocation, no per-file compiles, no DFP.
        # Keep the same source set and include order; the driver adds its
        example_name, _ = _example_name_and_config(manifest, module, mcu, variant)
        # Pure-logic sizechecks carry their own EPIC_CONFIG (or none).
        if toolchain == "epic-cc" and module in ("epic-fsm", "epic-pid", "epic-encoder", "epic-debounce", "epic-bus", "epic-lcd", "epic-mcp23x17", "epic-adcfilter") and variant == "target":
            has_config = False
            # Per-module basename so the drivers never collide in the
            # shared build dir: 16F877A-bus-sizecheck.hex etc.
            example_name = module.removeprefix("epic-") + "-sizecheck"
        else:
            has_config = emit_config_source(
                manifest, module, mcu, variant=variant, toolchain=toolchain, fosc_hz=fosc_hz
            ) is not None
        target = f"{build_dir}/{mcu}-{example_name}.hex"
        inc_flags = " ".join(f"-I{inc}" for inc in includes)
        # PIC part define is harmless under epic-cc and keeps the HAL's
        # #ifdef PIC16F877A paths intact; forward it.  Defining __EPIC_CC__
        # lets the HAL distinguish epic-cc from the host sim.
        def_flags = f"-D{_part_define(mcu)} -DFOSC_HZ={fosc_hz} -D__EPIC_CC__"
        srcs = " ".join(sources)
        if has_config:
            srcs += f" {objdir}/config_{mcu}.c"
        # Epic-cc's CLI: -I and -D are forwarded to clang, -o is hex, and
        # --target resolves the manifest mcu spelling (16F877A) itself, so no
        # name table lives here.
        cmd = f"{epic_cc} --target {mcu} {inc_flags} {def_flags} -o {target} {srcs}"
        out = [
            "#!/bin/sh",
            "# GENERATED by scripts/epic_build.py. Do not edit; regenerate.",
            f"# module={module} mcu={mcu} toolchain={toolchain}",
            "set -e",
            "",
            'cd "${EPIC_REPO_ROOT:-.}"',
            f"mkdir -p {objdir}",
            "",
            cmd,
            "",
            f'echo "Built {target}"',
        ]
        return "\n".join(out) + "\n"

    flags = []
    if dfp_dir:
        flags.append(f"-mdfp={dfp_dir}")
    flags.append(f"-mcpu={mcu.lower()}")
    # XC8-specific warning noise this repo has triaged: the "never
    # called" linker analysis (520/2053), the generated-no-code
    # expressions (759), the 64-bit-literal note (1516), the defaulted
    # config-word note (1311), the common-RAM top-boundary check
    # (1262), and the three advisory classes (1510/2098/1498). The
    # stack-depth warning (1393) is deliberately NOT suppressed: it is
    # the real 8-level-stack hazard class.
    flags += ["-O2", "-std=c99", "-Wall", "-Wextra",
              "-Wno-520", "-Wno-2053", "-Wno-759", "-Wno-1516",
              "-Wno-1311", "-Wno-1262", "-Wno-1510", "-Wno-2098",
              "-Wno-1498",
              # XC8's -Wall also turns on the gcc-style classes; the
              # harness report / math asm counters / sign-conversions
              # are triaged noise (the asm counters are referenced from
              # inline asm, invisible to the C-level unused analysis).
              "-Wno-unused-function", "-Wno-unused-variable",
              "-Wno-unused-parameter", "-Wno-sign-conversion",
              "-Wno-implicit-int-conversion",
              f"-D{_part_define(mcu)}"]
    flags += [f"-I{inc}" for inc in includes]
    flags.append(f"-DFOSC_HZ={fosc_hz}")
    cflags = " ".join(flags)

    example_name, _ = _example_name_and_config(manifest, module, mcu, variant)
    target = f"{build_dir}/{mcu}-{example_name}.hex"
    config_source = emit_config_source(
        manifest, module, mcu, variant=variant, toolchain=toolchain, fosc_hz=fosc_hz
    )

    out = [
        "#!/bin/sh",
        "# GENERATED by scripts/epic_build.py. Do not edit; regenerate.",
        f"# module={module} mcu={mcu}",
        "set -e",
        "",
        'cd "${EPIC_REPO_ROOT:-.}"',
        f"mkdir -p {objdir}",
        "",
    ]

    objs = []
    for src in sources:
        obj = f"{objdir}/{pathlib.Path(src).stem}.p1"
        objs.append(obj)
        out.append(f"xc8-cc {cflags} -c {src} -o {obj}")

    if config_source is not None:
        config_obj = f"{objdir}/config_{mcu}.p1"
        objs.append(config_obj)
        out += [
            "",
            f"xc8-cc {cflags} -c {objdir}/config_{mcu}.c -o {config_obj}",
        ]

    out += [
        "",
        f"xc8-cc {cflags} {' '.join(objs)} -o {target} -ginhx32",
        "",
        f'echo "Built {target}"',
    ]
    return "\n".join(out) + "\n"


def _part_define(mcu: str) -> str:
    """16F877A -> PIC16F877A, matching the Makefiles' CFLAGS_DEVICE."""
    return f"PIC{mcu}"


def parse_memory_summary(log: str):
    """Pull flash and RAM byte counts out of XC8's Memory Summary."""
    flash = re.search(r"Program space\s+used\s+\S+\s+\(\s*(\d+)\)", log)
    ram = re.search(r"Data space\s+used\s+\S+\s+\(\s*(\d+)\)", log)
    if not flash or not ram:
        return None
    return {"flash_bytes": int(flash.group(1)), "ram_bytes": int(ram.group(1))}


# XC8 manifest keys use Microchip's pragma names (FOSC, WDTE, PWRTE,
# BOREN, LVP, WRT, CPD, CP, ...); epic-cc's field table uses lower-case
# datasheet names (osc, wdt, pwrt, bor, lvp, wrt, ... - see
# epic-cc/crates/device/src/lib.rs).  Keep the table per-family so a
# PIC16 key does not shadow a PIC18 one.
_PIC16_XC8_TO_EPIC = {
    "fosc": "osc",
    "wdte": "wdt",
    "wdt": "wdt",
    "pwrte": "pwrt",
    "pwrt": "pwrt",
    "boren": "bor",
    "bor": "bor",
    "lvp": "lvp",
    "wrt": "wrt",
    "cpd": "cpd",
    "cp": "cp",
    "debug": "debug",
}

_PIC18_XC8_TO_EPIC = {
    "fosc": "osc",
    "plldiv": "plldiv",
    "cpudiv": "cpudiv",
    "usbdiv": "usbdiv",
    "ieso": "ieso",
    "fcmen": "fcmen",
    "vregen": "vregen",
    "bor": "boren",
    "boren": "boren",
    "borv": "borv",
    "pwrt": "pwrt",
    "wdt": "wdt",
    "wdte": "wdt",
    "wdtps": "wdtps",
    "mclre": "mclre",
    "lpt1osc": "lpt1osc",
    "pbaden": "pbaden",
    "ccp2mx": "ccp2mx",
    "debug": "debug",
    "xinst": "xinst",
    "lvp": "lvp",
    "stvren": "stvren",
    "cp0": "cp0",
    "cp1": "cp1",
    "cp2": "cp2",
    "cp3": "cp3",
    "cpb": "cpb",
    "cpd": "cpd",
    "wrt0": "wrt0",
    "wrt1": "wrt1",
    "wrt2": "wrt2",
    "wrt3": "wrt3",
    "wrtc": "wrtc",
    "wrtb": "wrtb",
    "wrtd": "wrtd",
    "ebtr0": "ebtr0",
    "ebtr1": "ebtr1",
    "ebtr2": "ebtr2",
    "ebtr3": "ebtr3",
    "ebtrb": "ebtrb",
}

_PIC18_VALUE_MAP = {
    "hs": "hs",
    "hspll": "hspll",
    "xt": "xt",
    "xtpll": "xtpll",
    "intosc": "intio",
    "5": "div5",
    "6": "div6",
    "10": "div10",
    "12": "div12",
    "1": "div1",
    "2": "div2",
    "3": "div3",
    "4": "div4",
    "osc1_pll2": "div2",
    "osc2_pll3": "div3",
    "osc3_pll4": "div4",
    "off": "off",
    "on": "on",
}


_BORV_MAP = {
    "0": "minimum",
    "1": "mid",
    "2": "low",
    "3": "maximum",
}

def _epic_config_spec(manifest, module, mcu, variant, fosc_hz):
    """Build the EPIC_CONFIG string for epic-cc from the manifest example."""
    fam = manifest.family_of(mcu)
    _, pragmas = _example_name_and_config(manifest, module, mcu, variant)
    if not pragmas:
        return None
    if fosc_hz is None:
        fosc_hz = fam.fosc_hz
    is_pic18 = fam.name == "PIC18Fxx5x"
    table = _PIC18_XC8_TO_EPIC if is_pic18 else _PIC16_XC8_TO_EPIC
    parts = []
    for key, val in sorted(pragmas.items()):
        low_key = key.lower()
        epic_key = table.get(low_key, low_key)
        # PIC16F887 uses `boren` as the field name; PIC16F877A uses `bor`.
        # The shared table maps `boren` -> `bor` for the 877A. Fix the 887
        # exemplar so the config validates against its own device TOML.
        if not is_pic18 and mcu.lower() == "16f887" and epic_key == "bor":
            epic_key = "boren"
        low_val = val.lower()
        if is_pic18:
            if low_key == "borv":
                epic_val = _BORV_MAP.get(low_val, low_val)
            elif low_key == "wdtps" and low_val.isdigit():
                epic_val = f"div{low_val}"
            else:
                epic_val = _PIC18_VALUE_MAP.get(low_val, low_val)
        else:
            epic_val = low_val
        parts.append(f"{epic_key}={epic_val}")
    parts.append(f"xtal_hz={fosc_hz}")
    return ", ".join(parts)

def _epiccc_include(path: str) -> str:
    """Map an XC8 family include dir to its epic-cc counterpart."""
    if "/include/target" in path:
        return path.replace("/include/target", "/include/epiccc")
    return path


def _display_path(path):
    """`path` written relative to the repository, or absolute when outside it.

    `--build-dir` may point anywhere, so the repo-relative form a reader
    expects is not always expressible.
    """
    try:
        return path.relative_to(REPO)
    except ValueError:
        return path


def cmd_build(args):
    manifest = epicmanifest.load(epicmanifest.default_path())
    toolchain = getattr(args, "toolchain", "xc8")
    epic_cc = getattr(args, "epic_cc", "epic-cc")
    try:
        script = emit_build_script(
            manifest, args.module, args.mcu,
            build_dir=args.build_dir, dfp_dir=args.dfp_dir, fosc_hz=args.fosc_hz,
            variant=args.variant, toolchain=toolchain, epic_cc=epic_cc,
        )
    except (UnsupportedError, epicmanifest.ManifestError) as exc:
        sys.exit(f"error: {exc}")

    objdir = (REPO / args.build_dir / args.mcu).resolve()
    objdir.mkdir(parents=True, exist_ok=True)
    config_source = emit_config_source(
        manifest, args.module, args.mcu, variant=args.variant,
        toolchain=toolchain, fosc_hz=args.fosc_hz,
    )
    if config_source is not None:
        (objdir / f"config_{args.mcu}.c").write_text(config_source)
    script_path = objdir / "build.sh"
    script_path.write_text(script)
    script_path.chmod(0o755)
    print(f"wrote {_display_path(script_path)}")

    if not args.run:
        return

    log_path = objdir / "build.log"
    proc = subprocess.run(
        ["sh", str(script_path)], cwd=REPO,
        capture_output=True, text=True,
        env={"EPIC_REPO_ROOT": str(REPO), "PATH": _path()},
    )
    log_path.write_text(proc.stdout + proc.stderr)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    if proc.returncode != 0:
        sys.exit(proc.returncode)
    usage = parse_memory_summary(log_path.read_text())
    if usage:
        print(f"flash {usage['flash_bytes']} bytes, RAM {usage['ram_bytes']} bytes")


def _path():
    import os
    return os.environ.get("PATH", "")


# Canonical per family: PR CI builds only this variant (half of
# variants x modules); nightly/schedule builds every variant.
CANONICAL = {
    "PIC16F87XA": "16F877A",
    "PIC16F88X": "16F887",
    "PIC18Fxx5x": "18F4550",
    "PIC16F193X": "16F1937",
}

def cmd_matrix(args):
    import os
    manifest = epicmanifest.load(epicmanifest.default_path())
    # --canonical-only or GITHUB_EVENT_NAME pull_request => canonical only
    canonical_only = bool(getattr(args, "canonical_only", False))
    if not canonical_only:
        env = os.environ.get("GITHUB_EVENT_NAME", "")
        if env == "pull_request":
            canonical_only = True
    entries = []
    for fam in manifest.families.values():
        modules = []
        for name in sorted(manifest.modules):
            mcus = manifest.modules[name].supported.get(fam.name, [])
            if not mcus or manifest.example_for(name, fam.name) is None:
                continue
            if canonical_only:
                canonical = CANONICAL.get(fam.name)
                if canonical and canonical in mcus:
                    mcus = [canonical]
                elif canonical:
                    # module does not support canonical (excluded) but supports family at all:
                    # pick first supported so the module still gets built on this family
                    mcus = [mcus[0]]
                else:
                    mcus = [mcus[0]]
            modules.append(f"{name}={','.join(mcus)}")
        if modules:
            entries.append({
                "family": fam.name,
                "dfp": fam.dfp,
                "modules": ";".join(modules),
            })
    if not entries:
        sys.exit("manifest yields no buildable (module, MCU) pairs")
    print(json.dumps(entries))


def cmd_report(args):
    usage = parse_memory_summary(pathlib.Path(args.log).read_text())
    if usage is None:
        sys.exit(f"no Memory Summary found in {args.log}")
    print(json.dumps(usage))


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    b = sub.add_parser("build", help="emit (and optionally run) a build script")
    b.add_argument("--module", required=True)
    b.add_argument("--mcu", required=True)
    b.add_argument("--build-dir", default="build")
    b.add_argument("--dfp-dir", default="",
                   help="device-pack directory for xc8 (ignored for epic-cc)")
    b.add_argument("--fosc-hz", type=int, default=None,
                   help="override the family's default oscillator frequency")
    b.add_argument("--variant", choices=["target", "sim"], default="target",
                   help="target (default): real-target firmware. sim: the "
                        "bounded, self-reporting build sim-tests.yml drives "
                        "under MPLAB SIM.")
    b.add_argument("--toolchain", choices=["xc8", "epic-cc"], default="xc8",
                   help="xc8 (default): emit an xc8-cc script with DFP and "
                        "Memory Summary parsing. epic-cc: emit an epic-cc "
                        "invocation with --target and EPIC_CONFIG.")
    b.add_argument("--epic-cc", default="epic-cc",
                   help="path to the epic-cc binary (only for --toolchain epic-cc)")
    b.add_argument("--run", action="store_true",
                   help="execute the script (needs xc8-cc or epic-cc on PATH)")
    b.set_defaults(func=cmd_build)

    m = sub.add_parser("matrix", help="print the CI build matrix as JSON")
    m.add_argument("--canonical-only", action="store_true", help="emit only the canonical variant per family (PR CI)")
    m.set_defaults(func=cmd_matrix)

    r = sub.add_parser("report", help="parse flash/RAM usage from a build log")
    r.add_argument("--log", required=True)
    r.set_defaults(func=cmd_report)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
