# scripts/epicurus_init.py
"""Project scaffolder for Epicurus: manifest in, ready main.c + Makefile +
patched MPLAB X .X out. Pure helpers here; scripts/epicurus.py is the CLI."""
from __future__ import annotations
import pathlib
import xml.etree.ElementTree as ET
import bundlegen, epicmanifest


class SelectionError(Exception):
    """A (family, part, module) selection the manifest says does not build."""


def hal_pseudo_module(manifest: epicmanifest.Manifest, fam: epicmanifest.Family) -> str:
    """The family's bare-HAL 'pseudo-module' (dir == hal_dir): the module
    whose example carries the working #pragma config set for the family."""
    for name, mod in manifest.modules.items():
        if mod.dir == fam.hal_dir:
            return name
    raise SelectionError(f"no HAL pseudo-module for {fam.name} (dir={fam.hal_dir})")


def resolve_selection(manifest, family_name, part, modules) -> list[str]:
    """Expand `modules` to an ordered, deduped (selected + deps) list,
    refusing any module unsupported on `part` with the manifest's reason."""
    if family_name not in manifest.families:
        raise SelectionError(f"unknown family {family_name!r}; "
                             f"known: {', '.join(sorted(manifest.families))}")
    fam = manifest.families[family_name]
    if part not in fam.variants:
        raise SelectionError(f"{part} is not a {family_name} part; "
                             f"known: {', '.join(fam.variants)}")
    known = set(bundlegen.modules_for_family(manifest, family_name))
    known.add(hal_pseudo_module(manifest, fam))
    ordered: list[str] = []
    seen: set[str] = set()
    for m in modules:
        if m not in known:
            raise SelectionError(f"unknown module {m!r} for {family_name}")
        for name in manifest.resolve_deps(m):
            if name in seen:
                continue
            if not manifest.is_supported(name, family_name, part):
                reason = manifest.exclusion_reason(name, part) or ""
                sup = manifest.modules[name].supported.get(family_name, [])
                raise SelectionError(
                    f"{name} is not supported on {part}"
                    + (f" ({reason})" if reason else "")
                    + f". Supported on {family_name}: {', '.join(sup) or 'none'}.")
            seen.add(name)
            ordered.append(name)
    return ordered


def emit_makefile(manifest, family_name, part, modules, bundle_dir, name) -> str:
    """The QUICKSTART.md six-line form, filled. `modules` are short names
    (epic- prefix dropped, as EPICURUS_MODULES expects)."""
    fam = manifest.families[family_name]
    mods = " ".join(modules)
    return "\n".join([
        f"# Generated by epicurus init. Edit freely.",
        f"EPICURUS_DIR := {bundle_dir}",
        f"EPICURUS_MCU := {part}",
        f"EPICURUS_MODULES := {mods}",
        f"include $(EPICURUS_DIR)/epicurus.mk",
        "",
        f"DFP := /opt/microchip/xc8/v4.00/pic/packs/$(EPICURUS_DFP)/xc8",
        "",
        "SRCS := main.c $(EPICURUS_SRCS)",
        "CFLAGS := -mdfp=$(DFP) -mcpu=$(shell echo $(EPICURUS_MCU) | tr A-Z a-z) \\",
        f"          -O2 -std=c99 -Wall -Wextra $(EPICURUS_CFLAGS) -DFOSC_HZ={fam.fosc_hz}",
        "",
        f"{name}.hex: $(SRCS)",
        "\txc8-cc $(CFLAGS) $^ -o $@ -ginhx32",
        "",
    ])

def _gpio_header(fam) -> str:
    """The family GPIO header path, e.g. peripherals/pic16f87xa_gpio.h."""
    base = fam.hal_dir.removesuffix("-hal")
    return f"peripherals/{base}_gpio.h"


def emit_main_c(manifest, family_name, part, modules) -> str:
    """A blink-on-epic-tick skeleton with the family's working #pragma config.
    The same source shape builds on all three families (the README blink
    example); only the GPIO header name is family-specific."""
    fam = manifest.families[family_name]
    pseudo = hal_pseudo_module(manifest, fam)
    example = manifest.example_for(pseudo, family_name, part)
    pragmas = example.config if example is not None else {}
    lines = [
        "/* Generated by epicurus init. Edit freely. */",
        "#include <xc.h>",
        '#include "epic_tick.h"',
        f'#include "{_gpio_header(fam)}"',
        "",
    ]
    lines += [f"#pragma config {k} = {v}" for k, v in pragmas.items()]
    lines += [
        "",
        "int main(void)",
        "{",
        "    EPIC_GPIO_Init(GPIOB, GPIO_PIN_0, GPIO_MODE_OUTPUT);",
        "    epic_tick_init(FOSC_HZ);",
        "",
        "    uint32_t last = epic_tick_get();",
        "    for (;;) {",
        "        if ((epic_tick_get() - last) >= 500u) {",
        "            last = epic_tick_get();",
        "            EPIC_GPIO_TogglePin(GPIOB, GPIO_PIN_0);",
        "        }",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def source_dirs(manifest, fam, part, selected) -> list[str]:
    """Repo-root-relative source directories: HAL (always full) + each
    resolved module's library source dirs. sourceRootList is directories,
    not files, so we collapse each source to its parent."""
    dirs: set[str] = set()
    for s in fam.hal_sources:
        dirs.add(str(pathlib.PurePosixPath(s).parent))
    for c in fam.conditional_sources:
        if part in c.variants:
            dirs.add(str(pathlib.PurePosixPath(c.path).parent))
    names: set[str] = set()
    for m in selected:
        names.update(manifest.resolve_deps(m))
    for name in names:
        mod = manifest.modules[name]
        for s in list(mod.sources) + list(mod.sources_by_family.get(fam.name, [])):
            dirs.add(f"{mod.dir}/{pathlib.PurePosixPath(s).parent}")
    return sorted(dirs)


def include_dirs(manifest, fam, part, selected) -> list[str]:
    """Family includes first (include/target before include, load-bearing),
    then each resolved module's includes, deduped."""
    out: list[str] = []
    seen: set[str] = set()
    for m in selected:
        for inc in manifest.includes_for(m, part):
            if inc not in seen:
                seen.add(inc)
                out.append(inc)
    return out


def patch_configurations_xml(xml_text, fam, part, selected_dirs, include_dirs) -> str:
    """Patch the four per-(part, subset) fields of a family's reference
    configurations.xml. ElementTree reformats the file; MPLAB X rewrites it
    on open, so formatting drift is harmless and the CI headless build gate
    proves the result still opens and builds."""
    root = ET.fromstring(xml_text)
    root.find(".//targetDevice").text = f"PIC{part}"
    for prop in root.findall(".//property[@key='define-macros']"):
        prop.set("value", f"PIC{part};FOSC_HZ={fam.fosc_hz}")
    inc_value = ";".join(f"../../{i}" for i in include_dirs)
    for prop in root.findall(".//property[@key='extra-include-directories']"):
        prop.set("value", inc_value)
    sr = root.find(".//sourceRootList")
    for elem in list(sr):
        sr.remove(elem)
    for d in selected_dirs:
        ET.SubElement(sr, "Elem").text = f"../../{d}"
    return ET.tostring(root, encoding="UTF-8", xml_declaration=True).decode()
