#!/usr/bin/env python3
"""Real-target build driver: manifest in, xc8-cc build script out.

Replaces the 29 hand-maintained mcu/*-mplabx/Makefiles. Resolution
(reading the manifest, resolving dependencies, computing the source and
include lists) happens here in Python; execution is a plain POSIX sh
script of xc8-cc invocations.

That split is not incidental. The toolchain container
(docker/ci-toolchain/Dockerfile) has no python3 in it, deliberately, so
a driver that called xc8-cc directly could not run where xc8-cc lives.
Emitting a script means resolution runs wherever python3 exists (a dev
host, or the GitHub runner, which already runs Python for CI discovery)
and execution needs only sh. The script is also a debugging artifact: it
records the exact command line for every translation unit, which suits a
codebase whose convention is to inspect generated output.

Usage:
  epic_build.py build --module epic-tick --mcu 16F877A --run
  epic_build.py matrix
  epic_build.py report --log build/16F877A/build.log
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import epicmanifest  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[1]


class UnsupportedError(Exception):
    """A (module, MCU) pair the manifest says does not build."""


def _check_supported(manifest, module, mcu):
    fam = manifest.family_of(mcu)
    if manifest.is_supported(module, fam.name, mcu):
        return fam
    reason = manifest.exclusion_reason(module, mcu)
    supported = manifest.modules[module].supported.get(fam.name, [])
    detail = ", ".join(supported) if supported else "none"
    raise UnsupportedError(
        f"{module} is not supported on {mcu}"
        + (f" ({reason})" if reason else "")
        + f". Supported on {fam.name}: {detail}."
    )


def emit_config_source(manifest, module, mcu):
    """The #pragma config translation unit, from manifest data.

    Returns None when the example has no config table at all (rather than
    a string with just the header), matching the Makefiles this replaces:
    epic-adcfilter/epic-fsm/epic-pid's Makefiles never compiled a config
    translation unit, and emitting an empty one would add a .p1 to the
    link they never produced, which is a hex diff waiting to happen
    (Amendment 2's correction).
    """
    fam = manifest.family_of(mcu)
    example = manifest.example_for(module, fam.name)
    pragmas = {} if example is None else example.config
    if not pragmas:
        return None
    lines = [
        "/* Auto-generated by scripts/epic_build.py. Do not edit. */",
        "#include <xc.h>",
    ]
    lines += [f"#pragma config {key} = {value}" for key, value in pragmas.items()]
    return "\n".join(lines) + "\n"


def emit_build_script(manifest, module, mcu, build_dir, dfp_dir, fosc_hz=None) -> str:
    """A self-contained POSIX sh script that produces the .hex.

    Flag order reproduces the Makefiles this replaces exactly (DFP, then
    -mcpu, then optimisation and warnings, then the part define, then
    includes, then FOSC_HZ). Byte-identical .hex output is the migration
    gate, and XC8's output is sensitive to command-line order, so this
    ordering is load-bearing, not cosmetic.

    fosc_hz defaults to the family's own value (a required manifest key,
    family-uniform); pass a value to override for a different crystal.
    """
    fam = _check_supported(manifest, module, mcu)
    example = manifest.example_for(module, fam.name)
    if example is None:
        raise UnsupportedError(f"{module} has no example for {fam.name} to build")
    if fosc_hz is None:
        fosc_hz = fam.fosc_hz

    sources = manifest.sources_for(module, mcu)
    includes = manifest.includes_for(module, mcu)
    objdir = f"{build_dir}/{mcu}"

    flags = []
    if dfp_dir:
        flags.append(f"-mdfp={dfp_dir}")
    flags.append(f"-mcpu={mcu.lower()}")
    flags += ["-O2", "-std=c99", "-Wall", "-Wextra", f"-D{_part_define(mcu)}"]
    flags += [f"-I{inc}" for inc in includes]
    flags.append(f"-DFOSC_HZ={fosc_hz}")
    cflags = " ".join(flags)

    target = f"{build_dir}/{mcu}-{example.name}.hex"
    config_source = emit_config_source(manifest, module, mcu)

    out = [
        "#!/bin/sh",
        "# GENERATED by scripts/epic_build.py. Do not edit; regenerate.",
        f"# module={module} mcu={mcu}",
        "set -e",
        "",
        'cd "${EPIC_REPO_ROOT:-.}"',
        f"mkdir -p {objdir}",
        "",
    ]

    objs = []
    for src in sources:
        obj = f"{objdir}/{pathlib.Path(src).stem}.p1"
        objs.append(obj)
        out.append(f"xc8-cc {cflags} -c {src} -o {obj}")

    if config_source is not None:
        config_obj = f"{objdir}/config_{mcu}.p1"
        objs.append(config_obj)
        out += [
            "",
            f"xc8-cc {cflags} -c {objdir}/config_{mcu}.c -o {config_obj}",
        ]

    out += [
        "",
        f"xc8-cc {cflags} {' '.join(objs)} -o {target} -ginhx32",
        "",
        f'echo "Built {target}"',
    ]
    return "\n".join(out) + "\n"


def _part_define(mcu: str) -> str:
    """16F877A -> PIC16F877A, matching the Makefiles' CFLAGS_DEVICE."""
    return f"PIC{mcu}"


def parse_memory_summary(log: str):
    """Pull flash and RAM byte counts out of XC8's Memory Summary."""
    flash = re.search(r"Program space\s+used\s+\S+\s+\(\s*(\d+)\)", log)
    ram = re.search(r"Data space\s+used\s+\S+\s+\(\s*(\d+)\)", log)
    if not flash or not ram:
        return None
    return {"flash_bytes": int(flash.group(1)), "ram_bytes": int(ram.group(1))}


def cmd_build(args):
    manifest = epicmanifest.load(epicmanifest.default_path())
    try:
        script = emit_build_script(
            manifest, args.module, args.mcu,
            build_dir=args.build_dir, dfp_dir=args.dfp_dir, fosc_hz=args.fosc_hz,
        )
    except (UnsupportedError, epicmanifest.ManifestError) as exc:
        sys.exit(f"error: {exc}")

    objdir = REPO / args.build_dir / args.mcu
    objdir.mkdir(parents=True, exist_ok=True)
    config_source = emit_config_source(manifest, args.module, args.mcu)
    if config_source is not None:
        (objdir / f"config_{args.mcu}.c").write_text(config_source)
    script_path = objdir / "build.sh"
    script_path.write_text(script)
    script_path.chmod(0o755)
    print(f"wrote {script_path.relative_to(REPO)}")

    if not args.run:
        return

    log_path = objdir / "build.log"
    proc = subprocess.run(
        ["sh", str(script_path)], cwd=REPO,
        capture_output=True, text=True,
        env={"EPIC_REPO_ROOT": str(REPO), "PATH": _path()},
    )
    log_path.write_text(proc.stdout + proc.stderr)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    if proc.returncode != 0:
        sys.exit(proc.returncode)
    usage = parse_memory_summary(log_path.read_text())
    if usage:
        print(f"flash {usage['flash_bytes']} bytes, RAM {usage['ram_bytes']} bytes")


def _path():
    import os
    return os.environ.get("PATH", "")


def cmd_matrix(args):
    manifest = epicmanifest.load(epicmanifest.default_path())
    entries = []
    for fam in manifest.families.values():
        modules = []
        for name in sorted(manifest.modules):
            mcus = manifest.modules[name].supported.get(fam.name, [])
            if mcus and manifest.example_for(name, fam.name) is not None:
                modules.append(f"{name}={','.join(mcus)}")
        if modules:
            entries.append({
                "family": fam.name,
                "dfp": fam.dfp,
                "modules": ";".join(modules),
            })
    if not entries:
        sys.exit("manifest yields no buildable (module, MCU) pairs")
    print(json.dumps(entries))


def cmd_report(args):
    usage = parse_memory_summary(pathlib.Path(args.log).read_text())
    if usage is None:
        sys.exit(f"no Memory Summary found in {args.log}")
    print(json.dumps(usage))


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    b = sub.add_parser("build", help="emit (and optionally run) a build script")
    b.add_argument("--module", required=True)
    b.add_argument("--mcu", required=True)
    b.add_argument("--build-dir", default="build")
    b.add_argument("--dfp-dir", default="")
    b.add_argument("--fosc-hz", type=int, default=None,
                   help="override the family's default oscillator frequency")
    b.add_argument("--run", action="store_true", help="execute the script (needs xc8-cc)")
    b.set_defaults(func=cmd_build)

    m = sub.add_parser("matrix", help="print the CI build matrix as JSON")
    m.set_defaults(func=cmd_matrix)

    r = sub.add_parser("report", help="parse flash/RAM usage from a build log")
    r.add_argument("--log", required=True)
    r.set_defaults(func=cmd_report)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
